### ISSUE TITLE
test fail- networkx version problem?

### ISSUE THREAD

**Issue by bendichter** [nipy/nipype#1054]
I am trying to confirm a correct installation of nipype. I pipped it and tried to run the test script.

I ran: 
`python -c "import nipype; nipype.test()"`

output:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bendichter/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nipype/__init__.py", line 77, in <module>
    from pipeline import Node, MapNode, JoinNode, Workflow
  File "/Users/bendichter/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nipype/pipeline/__init__.py", line 8, in <module>
    from engine import Node, MapNode, JoinNode, Workflow
  File "/Users/bendichter/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 43, in <module>
    package_check('networkx', '1.3')
  File "/Users/bendichter/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nipype/utils/misc.py", line 189, in package_check
    raise exc_failed_import(msg)
ImportError: Nipype requires networkx with version >= 1.3`

however when I run:
`pip freeze`
I get
`...
networkx==1.9.1
...`

I'm on a mac

**Comment by chrisfilo** [comment]
What do you get when you type:

	python -c "import networkx; print networkx.__version__"

**Comment by bendichter** [comment]
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bendichter/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/networkx/__init__.py", line 56, in <module>
    import networkx.utils
  File "/Users/bendichter/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/networkx/utils/__init__.py", line 2, in <module>
    from networkx.utils.decorators import *
  File "/Users/bendichter/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/networkx/utils/decorators.py", line 7, in <module>
    from decorator import decorator
ImportError: No module named decorator`

**Comment by bendichter** [comment]
reading through, I see the networkx dependency is listed as NetworkX 1.0 - 1.8. Let me try downgrading. I hope this doesn't brake something else...

**Comment by chrisfilo** [comment]
I'm working with 1.9.1 without problems. It seems that your networkx install is broken though (independently of nipype). I recommend reinstalling and if that does not work getting in touch with networkx developers/users.

**Comment by bendichter** [comment]
FIXED!

`$ rm -r //User/lib/python2.7/site-packages/networkx`

`$ rm -r //User/lib/python2.7/site-packages/networkx-1.9.1.dist-info/`

`$ sudo pip install networkx --upgrade`

`$ python -c "import nipype; nipype.test()"`

thanks, Chris
