### ISSUE TITLE
problem with inputs for rsfmri pipeline example

### ISSUE THREAD

**Issue by mb3152** [nipy/nipype#1063]
I am running the rsfmri pipeline like:

'python nipype_preprocessing.py -d /home/despo/rstate/read-only/Rest.ShamTMS/BACKUP_DICOM/114/DICOM/EPI9613TR1_6/IM-0006-0007.dcm -f /home/despo/mb3152/rsfmri/epi_data/114/EPI9613TR1_6/EPI9613TR1.nii -t /home/despo/mb3152/rsfmri/OASIS-30_Atropos_template_in_MNI152_2mm.nii.gz -s 114 -o /home/despo/mb3152/rsfmri/output --subjects_dir /home/despo/mb3152/rsfmri/fs_rsfmri'

but I keep getting 
Traceback (most recent call last):
  File "nipype_preprocessing.py", line 1027, in <module>
    wf = create_resting_workflow(args)
  File "nipype_preprocessing.py", line 978, in create_resting_workflow
    wf = create_workflow(**kwargs)
  File "nipype_preprocessing.py", line 636, in create_workflow
    registration = create_reg_workflow(name='registration')
  File "nipype_preprocessing.py", line 422, in create_reg_workflow
    convert = Node(freesurfer.MRIConvert(out_type='nii'),
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/interfaces/freesurfer/base.py", line 105, in __init__
    self.inputs.subjects_dir = self._subjects_dir
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/interfaces/traits_extension.py", line 168, in validate
    self.error( object, name, value )
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/traits/trait_handlers.py", line 169, in error
    value )
traits.trait_errors.TraitError: The 'subjects_dir' trait of a MRIConvertInputSpec instance must be an existing directory name, but a value of '/home/mb3152/rsfmri/fs_rsfmri/' <type 'str'> was specified.

why does it change what I pass as subjects_dir?

**Comment by satra** [comment]
do you by any chance have an environmental variable `SUBJECTS_DIR` that is different?

**Comment by mb3152** [comment]
You read my mind. I woke up this morning and realized that might be the problem! It works now.

Also, I am assuming it requires that I have run freesurfers recon all on the subject. Is that true?

**Comment by satra** [comment]
correct - that script does rely on freesurfer output.
