### ISSUE TITLE
SpaceTimeRealigner version problem?

### ISSUE THREAD

**Issue by mb3152** [nipy/nipype#1066]
I have the latest version of nipy, but it is claiming my SpaceTimeRealinger is not current enough?

Exception: Trait in_file (SpaceTimeRealigner) (version 0.3.0 < required 0.4.0.dev)

This is the full error:
150227-08:59:35,648 workflow INFO:
	 Executing node spacetime_realign in dir: /home/despo/mb3152/rsfmri/resting_114/spacetime_realign
150227-08:59:36,58 workflow ERROR:
	 ['Node spacetime_realign failed to run on host nx16.priv.']
150227-08:59:36,72 workflow INFO:
	 Saving crash info to /home/despo/mb3152/rsfmri/crash-20150227-085936-mb3152-spacetime_realign.pklz
150227-08:59:36,72 workflow INFO:
	 Traceback (most recent call last):
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 966, in run
    self._check_version_requirements(self.inputs)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 929, in _check_version_requirements
    version, min_ver))
Exception: Trait in_file (SpaceTimeRealigner) (version 0.3.0 < required 0.4.0.dev)

150227-08:59:36,93 workflow INFO:
	 ***********************************
150227-08:59:36,93 workflow ERROR:
	 could not run node: resting_114.spacetime_realign
150227-08:59:36,93 workflow INFO:
	 crashfile: /home/despo/mb3152/rsfmri/crash-20150227-085936-mb3152-spacetime_realign.pklz
150227-08:59:36,93 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "nipype_preprocessing.py", line 1025, in <module>
    wf.run(args.plugin)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 700, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 56, in run
    report_nodes_not_run(notrun)
  File "/home/despo/mb3152/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 92, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by mwaskom** [comment]
Nipy has not done a release in a long time, you'll need to install current github master to use that interface.

**Comment by mb3152** [comment]
Okay, you mean the current Nipy git, right?

**Comment by mwaskom** [comment]
yes

**Comment by mb3152** [comment]
Thanks, that seems to have fixed it!
