### ISSUE TITLE
Create interface for external function?

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1097]
In reaction to the lack of reaction [over here](https://github.com/nipy/nipype/issues/1095), I set out to try and wrap `dcmstack.parse_and_stack` for nipype myself.

I am doing this in accordance with [this guide](http://nipy.sourceforge.net/nipype/users/function_interface.html).

Here is my code:

```
import nipype.pipeline.engine as pe
from nipype.interfaces.utility import Function
import dcmstack

parser_stacker = pe.Node(name="parsestacker", interface=Function(input_names=[],output_names=['out_file'],function=dcmstack.parse_and_stack))
parser_stacker.inputs.src_paths = "/home/chymera/data2/dc.rs/export_ME/dicom/4457/1/EPI/"

pipeline = pe.Workflow(name='nipype_demo')
pipeline.add_nodes([parser_stacker])
pipeline.run()
pipeline.write_graph(graph2use='flat')
```

And here is the error output (you can test it yourself, since it fails before actually doing anythign with the data):

```
150504-11:47:51,121 workflow INFO:
	 ['check', 'execution', 'logging']
150504-11:47:51,132 workflow INFO:
	 Running serially.
150504-11:47:51,132 workflow INFO:
	 Executing node parsestacker in dir: /tmp/tmpGDVRBe/nipype_demo/parsestacker
150504-11:47:51,154 workflow ERROR:
	 ['Node parsestacker failed to run on host zenbookhost.']
150504-11:47:51,156 workflow INFO:
	 Saving crash info to /home/chymera/src/chyMRI/crash-20150504-114751-chymera-parsestacker.pklz
150504-11:47:51,156 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1003, in run
    runtime = self._run_interface(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/utility.py", line 437, in _run_interface
    self.imports)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/misc.py", line 91, in create_function_from_source
    raise RuntimeError(msg)
RuntimeError: name 'default_group_keys' is not defined
Error executing function:
 S"def parse_and_stack(src_paths, group_by=default_group_keys, extractor=None,\n                    force=False, warn_on_except=False, **stack_args):\n    '''Parse the given dicom files into a dictionary containing one or more\n    DicomStack objects.\n\n    Parameters\n    ----------\n    src_paths : sequence\n        A list of paths to the source DICOM files.\n\n    group_by : tuple\n        Meta data keys to group data sets with. Any data set with the same\n        values for these keys will be grouped together. This tuple of values\n        will also be the key in the result dictionary.\n\n    extractor : callable\n        Should take a dicom.dataset.Dataset and return a dictionary of the\n        extracted meta data.\n\n    force : bool\n        Force reading source files even if they do not appear to be DICOM.\n\n    warn_on_except : bool\n        Convert exceptions into warnings, possibly allowing some results to be\n        returned.\n\n    stack_args : kwargs\n        Keyword arguments to pass to the DicomStack constructor.\n    '''\n    results = parse_and_group(src_paths,\n                              group_by,\n                              extractor,\n                              force,\n                              warn_on_except)\n\n    for key, group in results.iteritems():\n        results[key] = stack_group(group, warn_on_except, **stack_args)\n\n    return results\n"
.
Functions in connection strings have to be standalone.
They cannot be declared either interactively or inside
another function or inline in the connect string. Any
imports should be done inside the function
Interface Function failed to run. 

150504-11:47:51,159 workflow INFO:
	 ***********************************
150504-11:47:51,160 workflow ERROR:
	 could not run node: nipype_demo.parsestacker
150504-11:47:51,160 workflow INFO:
	 crashfile: /home/chymera/src/chyMRI/crash-20150504-114751-chymera-parsestacker.pklz
150504-11:47:51,160 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/home/chymera/src/chyMRI/wrappers.py", line 10, in <module>
    pipeline.run()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 700, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 56, in run
    report_nodes_not_run(notrun)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 92, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
[Finished in 1.03s]
``` 

I was able to find [this thread](https://neurostars.org/p/689/) dealing with the same error, *but* the suggested fix (defining the function explicitly) is not applicable to my case. I want to use the dcmstack provided by upstream, not re-write it!

Can you help me ut?

**Comment by satra** [comment]
@TheChymera - you might be able to use the imports option here. 

https://github.com/nipy/nipype/blob/master/examples/rsfmri_vol_surface_preprocessing_nipy.py#L74
and
https://github.com/nipy/nipype/blob/master/examples/rsfmri_vol_surface_preprocessing_nipy.py#L725

the important thing is that we need to be able to pickle functions, send it over to a different machine, and execute it there. perhaps there are other ways of doing this.

**Comment by TheChymera** [comment]
Thank you very much, that solved my issue! 

But there is still something wrong with how I import the function, apparently:

With this code:

```
import nipype.pipeline.engine as pe
from nipype.interfaces.utility import Function
from dcmstack import parse_and_stack

imports = ["import os",
			"from dcmstack import *"
			]

parser_stacker = pe.Node(name="parsestacker", interface=Function(input_names=[], output_names=['out_file'], function=parse_and_stack, imports=imports))
parser_stacker.inputs.src_paths = "/home/chymera/data2/dc.rs/export_ME/dicom/4457/1/EPI/"

pipeline = pe.Workflow(name='nipype_demo')
pipeline.add_nodes([parser_stacker])
pipeline.run()
pipeline.write_graph(graph2use='flat')
```

I get:

```
150504-14:36:38,677 workflow INFO:
	 ['check', 'execution', 'logging']
150504-14:36:38,687 workflow INFO:
	 Running serially.
150504-14:36:38,689 workflow INFO:
	 Executing node parsestacker in dir: /tmp/tmpGWm10n/nipype_demo/parsestacker
150504-14:36:38,717 workflow ERROR:
	 ['Node parsestacker failed to run on host zenbookhost.']
150504-14:36:38,723 workflow INFO:
	 Saving crash info to /home/chymera/src/chyMRI/crash-20150504-143638-chymera-parsestacker.pklz
150504-14:36:38,724 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1003, in run
    runtime = self._run_interface(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/utility.py", line 437, in _run_interface
    self.imports)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/misc.py", line 93, in create_function_from_source
    assert len(ns_funcs) == 1, "Function or inputs are ill-defined"
AssertionError: Function or inputs are ill-defined
Interface Function failed to run. 

150504-14:36:38,731 workflow INFO:
	 ***********************************
150504-14:36:38,731 workflow ERROR:
	 could not run node: nipype_demo.parsestacker
150504-14:36:38,731 workflow INFO:
	 crashfile: /home/chymera/src/chyMRI/crash-20150504-143638-chymera-parsestacker.pklz
150504-14:36:38,732 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/home/chymera/src/chyMRI/wrappers.py", line 14, in <module>
    pipeline.run()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 700, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 56, in run
    report_nodes_not_run(notrun)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 92, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
[Finished in 2.248s]
```

Any ideas what I am doing wrong? I am guessing something regarding `input_names` or `output_names` - but what?

**Comment by satra** [comment]
input_names should list the order of inputs for the function, at least the mandatory ones, or the ones you need to set. we should update the Function code to automatically infer the inputs, but currently it doesn't.

**Comment by TheChymera** [comment]
ok, I am now using the exact same input names as [upstream](https://github.com/moloney/dcmstack/blob/master/src/dcmstack/dcmstack.py#L1124):

```
import nipype.pipeline.engine as pe
from nipype.interfaces.utility import Function
from dcmstack import parse_and_stack

imports = ["import os",
			"from dcmstack import *"
			]

parser_stacker = pe.Node(name="parsestacker", interface=Function(input_names=["src_paths", "group_by", "extractor", "force"], output_names=['out_file'], function=parse_and_stack, imports=imports))
parser_stacker.inputs.src_paths = "/home/chymera/data2/dc.rs/export_ME/dicom/4457/1/EPI/"
parser_stacker.inputs.group_by = "EchoTime"

pipeline = pe.Workflow(name='nipype_demo')
pipeline.add_nodes([parser_stacker])
pipeline.run()
pipeline.write_graph(graph2use='flat')
```

Any I stll get the same error - any ideas?

**Comment by TheChymera** [comment]
bump?

**Comment by TheChymera** [comment]
@satra 

Here is my nipype crashfile, are you sure you can't help me out?

```
chymera@desktophost ~/src/chyMRI $ nipype_display_crash /home/chymera/src/chyMRI/crash-20150517-211232-chymera-parsestacker.pklz


File: /home/chymera/src/chyMRI/crash-20150517-211232-chymera-parsestacker.pklz
Node: nipype_demo.parsestacker
Working directory: /tmp/tmpaUQzKy/nipype_demo/parsestacker


Node inputs:

extractor = <undefined>
force = <undefined>
function_str = S"def parse_and_stack(src_paths, group_by=default_group_keys, extractor=None,\n                    force=False, warn_on_except=False, **stack_args):\n    '''Parse the given dicom files into a dictionary containing one or more\n    DicomStack objects.\n\n    Parameters\n    ----------\n    src_paths : sequence\n        A list of paths to the source DICOM files.\n\n    group_by : tuple\n        Meta data keys to group data sets with. Any data set with the same\n        values for these keys will be grouped together. This tuple of values\n        will also be the key in the result dictionary.\n\n    extractor : callable\n        Should take a dicom.dataset.Dataset and return a dictionary of the\n        extracted meta data.\n\n    force : bool\n        Force reading source files even if they do not appear to be DICOM.\n\n    warn_on_except : bool\n        Convert exceptions into warnings, possibly allowing some results to be\n        returned.\n\n    stack_args : kwargs\n        Keyword arguments to pass to the DicomStack constructor.\n    '''\n    results = parse_and_group(src_paths,\n                              group_by,\n                              extractor,\n                              force,\n                              warn_on_except)\n\n    for key, group in results.iteritems():\n        results[key] = stack_group(group, warn_on_except, **stack_args)\n\n    return results\n"
.
group_by = EchoTime
ignore_exception = False
src_paths = /home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/



Traceback: 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1003, in run
    runtime = self._run_interface(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/utility.py", line 437, in _run_interface
    self.imports)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/misc.py", line 93, in create_function_from_source
    assert len(ns_funcs) == 1, "Function or inputs are ill-defined"
AssertionError: Function or inputs are ill-defined
Interface Function failed to run. 
```

**Comment by TheChymera** [comment]
and with this code:

```
import nipype.pipeline.engine as pe
from nipype.interfaces.utility import Function
from dcmstack import parse_and_stack

imports = ["import os",
            "from dcmstack import *"
            ]

parser_stacker_function = Function(input_names=["src_paths", "group_by", "extractor", "force", "function_str", "ignore_exception"],
                                    output_names=['out_file'],
                                    function=parse_and_stack,
                                    imports=imports)
print(parser_stacker_function.help())
parser_stacker = pe.Node(name="parsestacker", interface=parser_stacker_function)
parser_stacker.inputs.src_paths = "/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/"
parser_stacker.inputs.function_str = "parse_and_stack"
parser_stacker.inputs.group_by = "EchoTime"

pipeline = pe.Workflow(name='nipype_demo')
pipeline.add_nodes([parser_stacker])
pipeline.run()
pipeline.write_graph(graph2use='flat')
```

I get this crash report:


```
File: crash-20150517-212504-chymera-parsestacker.pklz
Node: nipype_demo.parsestacker
Working directory: /tmp/tmpxsvT4v/nipype_demo/parsestacker


Node inputs:

extractor = <undefined>
force = <undefined>
function_str = S'parse_and_stack'
p1
.
group_by = EchoTime
ignore_exception = <undefined>
src_paths = /home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/



Traceback: 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1003, in run
    runtime = self._run_interface(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/utility.py", line 437, in _run_interface
    self.imports)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/misc.py", line 93, in create_function_from_source
    assert len(ns_funcs) == 1, "Function or inputs are ill-defined"
AssertionError: Function or inputs are ill-defined
Interface Function failed to run. 
```

**Comment by satra** [comment]
can you try it without this:

`parser_stacker.inputs.function_str = "parse_and_stack"`

**Comment by TheChymera** [comment]
@satra the first example was without `parser_stacker.inputs.function_str = "parse_and_stack"`.

Also, I tried this:

```
import nipype.pipeline.engine as pe
from nipype.interfaces.utility import Function
import os

data_dir = "/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/"
file_list = [data_dir+file for file in os.listdir(data_dir)]

imports = ["import os",
			"from dcmstack import *"
			]

default_group_keys =  ('SeriesInstanceUID',
						'SeriesNumber',
						'ProtocolName',
						'ImageOrientationPatient')

def parse_and_stack_wrapper(src_paths, group_by=default_group_keys, extractor=None, force=False, warn_on_except=False):
	from dcmstack import parse_and_stack
	return parse_and_stack(src_paths, group_by=group_by, extractor=extractor, force=force, warn_on_except=warn_on_except)


parser_stacker_function = Function(input_names=["src_paths", "group_by", "extractor", "force", "warn_on_except"],
									output_names=['out_file'],
									function=parse_and_stack_wrapper,
									imports=imports)

parser_stacker = pe.Node(name="parsestacker", interface=parser_stacker_function)
parser_stacker.inputs.src_paths = file_list
parser_stacker.inputs.group_by = "EchoTime"

pipeline = pe.Workflow(name='nipype_demo')
pipeline.add_nodes([parser_stacker])
pipeline.run()
pipeline.write_graph(graph2use='flat')
```

and I get 

```
TypeError: can't pickle function objects
```

In the traceback, and this:

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/nipype_display_crash", line 85, in <module>
    debug, args.directory)
  File "/usr/lib/python-exec/python2.7/nipype_display_crash", line 17, in display_crash_files
    crash_data = loadcrash(crashfile)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/filemanip.py", line 381, in loadcrash
    return loadpkl(infile)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/filemanip.py", line 402, in loadpkl
    return cPickle.load(pkl_file)
EOFError
```

when I try to open the progress report.

**Comment by TheChymera** [comment]
And, my latest attempt:

```
import nipype.pipeline.engine as pe
from nipype.interfaces.utility import Function
import os
import dcmstack

data_dir = "/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/"
file_list = [data_dir+file for file in os.listdir(data_dir)]

imports = ["import os",
			"from dcmstack.dcmstack import *",
			"from dcmstack import*",
			"import warnings, re, dicom",
			"from copy import deepcopy",
			"import nibabel as nb",
			"from nibabel.nifti1 import Nifti1Extensions",
			"from nibabel.spatialimages import HeaderDataError",
			"from nibabel.orientations import (io_orientation, apply_orientation, inv_ornt_aff)",
			"import numpy as np"
			]

default_group_keys =  ('SeriesInstanceUID',
						'SeriesNumber',
						'ProtocolName',
						'ImageOrientationPatient')

def parse_and_stack_wrapper(src_paths, group_by=default_group_keys, extractor=None, force=False, warn_on_except=False):
	from dcmstack import parse_and_stack
	return parse_and_stack(src_paths, group_by=group_by, extractor=extractor, force=force, warn_on_except=warn_on_except)


parser_stacker_function = Function(input_names=["src_paths", "group_by", "extractor", "force", "warn_on_except"],
									output_names=['out_file'],
									function=dcmstack.dcmstack.parse_and_stack,
									imports=imports)

parser_stacker = pe.Node(name="parsestacker", interface=parser_stacker_function)
parser_stacker.inputs.src_paths = file_list[:20]
parser_stacker.inputs.group_by = "EchoTime"

pipeline = pe.Workflow(name='nipype_demo')
pipeline.add_nodes([parser_stacker])
pipeline.run()
pipeline.write_graph(graph2use='flat')
```

gives me:

```
File: crash-20150518-134925-chymera-parsestacker.pklz
Node: nipype_demo.parsestacker
Working directory: /tmp/tmpKnyxD5/nipype_demo/parsestacker


Node inputs:

extractor = <undefined>
force = <undefined>
function_str = S"def parse_and_stack(src_paths, group_by=default_group_keys, extractor=None,\n                    force=False, warn_on_except=False, **stack_args):\n    '''Parse the given dicom files into a dictionary containing one or more\n    DicomStack objects.\n\n    Parameters\n    ----------\n    src_paths : sequence\n        A list of paths to the source DICOM files.\n\n    group_by : tuple\n        Meta data keys to group data sets with. Any data set with the same\n        values for these keys will be grouped together. This tuple of values\n        will also be the key in the result dictionary.\n\n    extractor : callable\n        Should take a dicom.dataset.Dataset and return a dictionary of the\n        extracted meta data.\n\n    force : bool\n        Force reading source files even if they do not appear to be DICOM.\n\n    warn_on_except : bool\n        Convert exceptions into warnings, possibly allowing some results to be\n        returned.\n\n    stack_args : kwargs\n        Keyword arguments to pass to the DicomStack constructor.\n    '''\n    results = parse_and_group(src_paths,\n                              group_by,\n                              extractor,\n                              force,\n                              warn_on_except)\n\n    for key, group in results.iteritems():\n        results[key] = stack_group(group, warn_on_except, **stack_args)\n\n    return results\n"
.
group_by = EchoTime
ignore_exception = False
src_paths = ['/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm29433.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm22441.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm13447.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm31541.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm01853.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm24523.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm06882.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm00072.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm20589.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm16920.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm29071.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm01730.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm15798.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm22918.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm29277.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm14003.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm34761.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm14924.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm27447.dcm', '/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/MRIm30951.dcm']
warn_on_except = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1003, in run
    runtime = self._run_interface(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/utility.py", line 437, in _run_interface
    self.imports)
  File "/usr/lib64/python2.7/site-packages/nipype/utils/misc.py", line 93, in create_function_from_source
    assert len(ns_funcs) == 1, "Function or inputs are ill-defined"
AssertionError: Function or inputs are ill-defined
Interface Function failed to run. 
```

The Node inputs all seem right to me - @moloney, any ideas maybe?

**Comment by satra** [comment]
@TheChymera - i was able to try this out on a file. the error is due to the fact that dcmstack returns a non-pickle-able object:

```
from nipype.utils.filemanip import savepkl
foo = parse_and_stack_wrapper(file_list, force=True)
savepkl('test.pkl', foo)
```
raises the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-2de85cd8ff75> in <module>()
      1 from nipype.utils.filemanip import savepkl
      2 foo = parse_and_stack_wrapper(file_list, force=True)
----> 3 savepkl('test.pkl', foo)

/software/nipy-repo/nipype/nipype/utils/filemanip.pyc in savepkl(filename, record)
    408     else:
    409         pkl_file = open(filename, 'wb')
--> 410     cPickle.dump(record, pkl_file)
    411     pkl_file.close()
    412 

/software/anaconda/envs/devpype/lib/python2.7/copy_reg.pyc in _reduce_ex(self, proto)
     68     else:
     69         if base is self.__class__:
---> 70             raise TypeError, "can't pickle %s objects" % base.__name__
     71         state = base(self)
     72     args = (self.__class__, base, state)

TypeError: can't pickle function objects
```

so first you should make sure the output returned by any function is pickleable and then try to use it in the Function Node.

**Comment by TheChymera** [comment]
@satra what about my last example where I do not try to write a wrapper (`parse_and_stack_wrapper`) and instead try to import `parse_and_stack` directly from the upstream package?

I keep getting `AssertionError: Function or inputs are ill-defined`. What can I do about that?

how can I make my function pickleable?

**Comment by satra** [comment]
@TheChymera - it's not that your function is pickleable, it's that the function you are using from dcmstack returns an output that is pickleable

**Comment by TheChymera** [comment]
@satra any ideas how I can make the function picklable?

**Comment by TheChymera** [comment]
solved in [this issue](https://github.com/nipy/nipype/issues/1107).
