### ISSUE TITLE
Cleanup for MapNode

### ISSUE THREAD

**Issue by blakedewey** [nipy/nipype#1139]
It seems that some of my workflows will randomly error out when a MapNode finishes. I can't seem to figure out what would cause this, but it seems to be in the cleanup of the "batch" directory.

Traceback (most recent call last):
  File "/shared/analyzed/02233496/20030925-18663/working/coreg/batch/pyscript_20150713_183311_coreg_transform_secondary.py", line 32, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/p4/PipelineSoftware/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/p4/PipelineSoftware/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 2338, in _run_interface
    shutil.rmtree(path)
  File "/p4/PipelineSoftware/anaconda/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/p4/PipelineSoftware/anaconda/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 2] No such file or directory: '/shared/analyzed/02233496/20030925-18663/working/coreg/transform_secondary/mapflow/batch/J_transform_secondary2.tnu_svc.o975033'

**Comment by djarecka** [comment]
do you still have this problem? If yes, can you please tell me how can I reproduce the problem?

**Comment by satra** [comment]
@blakedewey - is it possible that you were running the same workflow simultaneously as two separate instances? there is not locking between instances of workflows run with the same output directory.

**Comment by blakedewey** [comment]
It is possible, but also unlikely. This was so long ago, that I don't remember the exact instance where it occurred. Closing this, for now, would be fine with me.
