### ISSUE TITLE
AttributeError: 'PolyDataWriter' object has no attribute 'set_input_data'

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#1218]
```
> DISPLAY= PYTHONPATH=/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/debian/python-nipype/usr/lib/python2.7/site-packages MPLCONFIGDIR=/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/build xvfb-run -s "-screen 0 1024x768x24 -ac  +render -noreset" nosetests nipype.algorithms.tests.test_mesh_ops
Xlib:  extension "RANDR" missing on display ":99".
EE
======================================================================
ERROR: Failure: AttributeError ('PolyDataWriter' object has no attribute 'set_input_data'
Interface ComputeMeshWarp failed to run. )
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 153, in skipper_gen
    for x in f(*args, **kwargs):
  File "/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/debian/python-nipype/usr/lib/python2.7/site-packages/nipype/algorithms/tests/test_mesh_ops.py", line 35, in test_ident_distances
    res = dist_ident.run()
  File "/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/debian/python-nipype/usr/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1033, in run
    runtime = self._run_wrapper(runtime)
  File "/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/debian/python-nipype/usr/lib/python2.7/site-packages/nipype/interfaces/base.py", line 983, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/debian/python-nipype/usr/lib/python2.7/site-packages/nipype/algorithms/mesh.py", line 283, in _run_interface
    writer.set_input_data(out_mesh)
AttributeError: 'PolyDataWriter' object has no attribute 'set_input_data'
Interface ComputeMeshWarp failed to run. 
-------------------- >> begin captured logging << --------------------
rdflib: INFO: RDFLib Version: 4.1.2
interface: INFO: Redirecting X to :1099
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: AttributeError ('PolyDataWriter' object has no attribute 'set_input_data')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 153, in skipper_gen
    for x in f(*args, **kwargs):
  File "/home/yoh/proj/nipy/nipy-suite/build-area/nipype-0.11.0/debian/python-nipype/usr/lib/python2.7/site-packages/nipype/algorithms/tests/test_mesh_ops.py", line 62, in test_trans_distances
    writer.set_input_data(vtk1)
AttributeError: 'PolyDataWriter' object has no attribute 'set_input_data'

----------------------------------------------------------------------
Ran 2 tests in 0.626s

FAILED (errors=2)
```

which version of tvtk (mayavi2) do you need? we have 4.3.1-4.1 on debian sid/stretch atm

**Comment by oesteban** [comment]
What version of vtk is installed? (<6.0 I assume)
