### ISSUE TITLE
dcm2nii interface fails with Philips DTI DICOM series

### ISSUE THREAD

**Issue by mih** [nipy/nipype#1224]
Running via https://github.com/nipy/heudiconv

Here is the error:

```
150921-09:25:41,93 workflow INFO:
     Executing node convert in dir: /tmp/heudiconvtmp2HDSgn/convert
150921-09:25:44,376 workflow INFO:
     Running: dcm2nii -a y -c y -b config.ini -v y -d y -e y -g y -i n -n y -o /tmp/heudiconvtmp2HDSgn/convert -p y -x n -f n /tmp/heudiconvtmp2HDSgn/convert/MR.1.3.46.670589.11.38317.5.0.4960.2013071215014404226
Traceback (most recent call last):
  File "/home/mih/hacking/heudiconv/bin/heudiconv", line 477, in <module>
    anon_outdir=args.conv_outputdir)
  File "/home/mih/hacking/heudiconv/bin/heudiconv", line 417, in convert_dicoms
    convert(cinfo, converter=converter)
  File "/home/mih/hacking/heudiconv/bin/heudiconv", line 287, in convert
    res = convertnode.run()
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1004, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1098, in aggregate_outputs
    raise FileNotFoundError(msg)
nipype.utils.filemanip.FileNotFoundError: File/Directory '['/tmp/heudiconvtmp2HDSgn/convert/20130712_141141DTIhigh2isoSENSEs701a1007.bvec']' not found for Dcm2nii output 'bvecs'.
Interface Dcm2nii failed to run. 
```

However, the actual dcm2nii call was successful and generated the expected output, except for an 'x' prefix:

```
% ls /tmp/heudiconvtmp2HDSgn/convert/*.b*
/tmp/heudiconvtmp2HDSgn/convert/x20130712_141141DTIhigh2isoSENSEs701a1007.bval
/tmp/heudiconvtmp2HDSgn/convert/x20130712_141141DTIhigh2isoSENSEs701a1007.bvec
```

**Comment by cni-md** [comment]
Is this still a problem? With nipype 0.12.0-rc1 and heudiconv it's working fine fpr nii, bvec, bval. Only dcmstack is unable to produce a json file for Philips DTI data.

**Comment by satra** [comment]
and now that dcm2niix has been merged, we should update heudiconv to use it (@mxgd). then we can get the BIDS sidecar json.

**Comment by cni-md** [comment]
I wrote a heudiconv interface for dcm2niix: Please check:
[https://github.com/cni-md/heudiconv.git](heudiconv)

At least for Philips data the BIDS sidecar is sparse (TR, TE, phase enc dir). For a replacement of the memory eating dcmstack I need more parameters.

**Comment by mgxd** [comment]
@mih is this all set?

**Comment by cni-md** [comment]
@mgxd dcm2niix is working fine for Philips standard DICOM. DTI, fieldmap, ... all working. I assume dcm2nii is depreciated because dcm2niix is much faster.
