### ISSUE TITLE
AFNItoNIFTI throws error if no out_file explicitly specified

### ISSUE THREAD

**Issue by sgiavasis** [nipy/nipype#1377]
Hi guys,

I'm using the interface for AFNItoNIFTI from afni/preprocess. If I don't supply an out_file name as one of the inputs, I get this error:

File: crash-20160225-130048-sgiavasis-segment_AFNItoNIFTI_.pklz
Node: afni_segmentation_workflow.segment_AFNItoNIFTI_
Working directory: /home/sgiavasis/gitrepos/afni_segmentation/afni_segmentation_workflow/segment_AFNItoNIFTI_

Node inputs:

args = <undefined>
environ = {}
ignore_exception = False
in_file = /home/sgiavasis/gitrepos/afni_segmentation/afni_segmentation_workflow/segmentation_/Segsy/Classes+orig.BRIK
out_file = <undefined>
outputtype = AFNI
terminal_output = stream

Traceback: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 19, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py", line 618, in _run_command
    cmd = self._interface.cmdline
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1417, in cmdline
    allargs = self._parse_inputs()
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1647, in _parse_inputs
    value = self._filename_from_source(name)
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1604, in _filename_from_source
    retval = self._overload_extension(retval, name)
TypeError: _overload_extension() takes exactly 2 arguments (3 given)

It seems like it has something to do with when it attempts to create its own out_file name through the name_source/name_template.

**Comment by chrisfilo** [comment]
This definitely should not break in such an ugly way, but one  other thing seems weird - outputtype is set to AFNI. Could you try setting it to NIFTI?

**Comment by sgiavasis** [comment]
Same thing:

File: crash-20160225-165313-sgiavasis-segment_AFNItoNIFTI_.pklz
Node: afni_segmentation_workflow.segment_AFNItoNIFTI_
Working directory: /home/sgiavasis/gitrepos/afni_segmentation/afni_segmentation_workflow/segment_AFNItoNIFTI_


Node inputs:

args = <undefined>
environ = {}
ignore_exception = False
in_file = /home/sgiavasis/gitrepos/afni_segmentation/afni_segmentation_workflow/segmentation_/Segsy/Classes+orig.BRIK
out_file = <undefined>
outputtype = NIFTI
terminal_output = stream



Traceback: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 19, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py", line 618, in _run_command
    cmd = self._interface.cmdline
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1417, in cmdline
    allargs = self._parse_inputs()
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1647, in _parse_inputs
    value = self._filename_from_source(name)
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1604, in _filename_from_source
    retval = self._overload_extension(retval, name)
TypeError: _overload_extension() takes exactly 2 arguments (3 given)

**Comment by umeboshi7** [comment]
I think this is due to the fact that the name source is the input file, and the _list_outputs of AFNICommand adds a '+orig.BRIK' if no inputs.out_file is given.
I've had issues with this, and the only easy solution is to give an output name with the extension included

**Comment by sgiavasis** [comment]
Yup, that's what I'm doing for now and it works fine that way.

Thanks.

**Comment by mgxd** [comment]
closing this - feel free to reopen
