### ISSUE TITLE
xvfbwrapper error

### ISSUE THREAD

**Issue by satra** [nipy/nipype#1400]
@oesteban - i'm getting this on my osx machine which has Xvfb

```
======================================================================
ERROR: Failure: RuntimeError (Xvfb did not start
Interface ComputeMeshWarp failed to run. )
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/software/nipy-repo/nipype/nipype/algorithms/tests/test_mesh_ops.py", line 29, in test_ident_distances
    res = dist_ident.run()
  File "/software/nipy-repo/nipype/nipype/interfaces/base.py", line 1032, in run
    runtime = self._run_wrapper(runtime)
  File "/software/nipy-repo/nipype/nipype/interfaces/base.py", line 980, in _run_wrapper
    vdisp.start()
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/xvfbwrapper-0.2.8-py2.7.egg/xvfbwrapper.py", line 63, in start
    raise RuntimeError('Xvfb did not start')
RuntimeError: Xvfb did not start
Interface ComputeMeshWarp failed to run. 

======================================================================
ERROR: Failure: RuntimeError (Xvfb did not start
Interface ComputeMeshWarp failed to run. )
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/software/nipy-repo/nipype/nipype/algorithms/tests/test_mesh_ops.py", line 68, in test_trans_distances
    res = dist.run()
  File "/software/nipy-repo/nipype/nipype/interfaces/base.py", line 1032, in run
    runtime = self._run_wrapper(runtime)
  File "/software/nipy-repo/nipype/nipype/interfaces/base.py", line 980, in _run_wrapper
    vdisp.start()
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/xvfbwrapper-0.2.8-py2.7.egg/xvfbwrapper.py", line 63, in start
    raise RuntimeError('Xvfb did not start')
RuntimeError: Xvfb did not start
Interface ComputeMeshWarp failed to run. 

----------------------------------------------------------------------
```

more generally this is what Xvfb does in user mode:

```
$ Xvfb 
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
```

**Comment by oesteban** [comment]
Looks like a problem in the xvfbwrapper package, it seems to be assuming that there is a /tmp folder, right? Should we provide our modification under external?

**Comment by oesteban** [comment]
In my macbook pro I can reproduce your output.

When I run Xvfb as root, the problem is not there anymore, how can we solve this?

**Comment by oesteban** [comment]
https://discussions.apple.com/thread/7590534?start=0&tstart=0

This seems a MacOSX-only problem. I guess having XQuartz installed and pointing `$DISPLAY` to the correct port should suffice to avoid the need of Xvfb.

**Comment by satra** [comment]
>  I guess having XQuartz installed and pointing $DISPLAY to the correct port should suffice to avoid the need of Xvfb.

that's definitely a workaround, but not a solution, since the intent of the headless display is still very much needed. given this is an issue with perhaps specific combinations of software, we should offer a proper exception message on `sys.platform==darwin` when starting Xvfb returns with an error.
