### ISSUE TITLE
Experiencing fatal error with test suite

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1636]
I'm getting these 4 errors by running the nipype test suite (live HEAD):

```
======================================================================
ERROR: Failure: TypeError (constructor returned NULL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/__init__.py", line 4, in <module>
    from .utils import Similarity
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/utils.py", line 25, in <module>
    from nipy.algorithms.registration.histogram_registration import HistogramRegistration
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/__init__.py", line 18, in <module>
    from .scripting import space_time_realign, aff2euler
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/scripting.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3.py", line 58, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

======================================================================
ERROR: test_list_nipy_interfacesp (nipype.utils.tests.test_cmd.TestNipypeCMD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/tests/test_cmd.py", line 77, in test_list_nipy_interfacesp
    nipype_cmd.main(['nipype_cmd', 'nipype.interfaces.nipy'])
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/nipype_cmd.py", line 81, in main
    listClasses(argv[1])
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/nipype_cmd.py", line 15, in listClasses
    __import__(module)
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/__init__.py", line 4, in <module>
    from .utils import Similarity
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/utils.py", line 25, in <module>
    from nipy.algorithms.registration.histogram_registration import HistogramRegistration
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/__init__.py", line 18, in <module>
    from .scripting import space_time_realign, aff2euler
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/scripting.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3.py", line 58, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

======================================================================
ERROR: test_run_4d_realign_help (nipype.utils.tests.test_cmd.TestNipypeCMD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/tests/test_cmd.py", line 132, in test_run_4d_realign_help
    nipype_cmd.main(['nipype_cmd', 'nipype.interfaces.nipy', 'FmriRealign4d', '-h'])
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/nipype_cmd.py", line 91, in main
    interface_parser, interface = add_options(interface_parser, parsed.module, parsed.interface)
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/nipype_cmd.py", line 26, in add_options
    __import__(module)
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/__init__.py", line 4, in <module>
    from .utils import Similarity
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/utils.py", line 25, in <module>
    from nipy.algorithms.registration.histogram_registration import HistogramRegistration
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/__init__.py", line 18, in <module>
    from .scripting import space_time_realign, aff2euler
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/scripting.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3.py", line 58, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

======================================================================
ERROR: test_run_4d_realign_without_arguments (nipype.utils.tests.test_cmd.TestNipypeCMD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/tests/test_cmd.py", line 100, in test_run_4d_realign_without_arguments
    nipype_cmd.main(['nipype_cmd', 'nipype.interfaces.nipy', 'FmriRealign4d'])
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/nipype_cmd.py", line 91, in main
    interface_parser, interface = add_options(interface_parser, parsed.module, parsed.interface)
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/utils/nipype_cmd.py", line 26, in add_options
    __import__(module)
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/__init__.py", line 4, in <module>
    from .utils import Similarity
  File "/var/tmp/portage/sci-libs/nipype-9999/work/nipype-9999/nipype/interfaces/nipy/utils.py", line 25, in <module>
    from nipy.algorithms.registration.histogram_registration import HistogramRegistration
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/__init__.py", line 18, in <module>
    from .scripting import space_time_realign, aff2euler
  File "/usr/lib64/python2.7/site-packages/nipy/algorithms/registration/scripting.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3.py", line 58, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

```

Any idea what I can do about this? Am I missing some dependency?

**Comment by oesteban** [comment]
Seems like your matplotlib installation is set to use the ```gtk3``` backend.

I guess changing the default in the ```matplotlibrc``` file to ```agg``` would do. Also, adding this at the top of your entrypoint script should do:

```
import matplotlib
matplotlib.use('agg')
```

**Comment by TheChymera** [comment]
@satra said that snippet of code [should be imported before anything in the nipype library](https://github.com/nipy/nipype/issues/1635#issuecomment-247228322). Is it possible it's missing somewhere?

**Comment by oesteban** [comment]
I guess you are setting the matplotlib backend somewhere before (maybe shadowed by another tool)

**Comment by TheChymera** [comment]
I'm sorry. I believe this is again a nipy issue :-/ why does nipype test modules from nipy?
