### ISSUE TITLE
nipype 0.12.1 test failed

### ISSUE THREAD

**Issue by deajosha** [nipy/nipype#1691]
I downloaded nipype-0.12.1 source package under ubuntu-16.04 x64 system.
and then run the command on the terminal to install it : sudo pip install nipype-0.12.1.tar.gz.
install all the dependancies as writed in requirements.txt.
after that, run the test command on the page http://nipype.readthedocs.io/en/0.12.1/users/install.html:
sudo python -c "import nipype;nipype.test()"
it ocurred:
Exeeption: Subnodes of node: n1 failed:
Subnode 0 failed
Error:
can only concatenate list(not "int")to list
Interface Function failed to run.
Subnode 2 failed
Error:
can only concatenate list(not "int")to list
Interface Function failed to run.

I just don't know why this happen.

**Comment by satra** [comment]
@deajosha - could you please give us the final output of that command? it should say something like:

```
Ran ... tests in ...s

ERROR (SKIP=..., FAILED=..., ERRORS=...)
```

**Comment by deajosha** [comment]
`======================================================================
FAIL: Doctest: nipype.interfaces.bru2nii.Bru2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for nipype.interfaces.bru2nii.Bru2
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/bru2nii.py", line 26, in Bru2

----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/bru2nii.py", line 34, in nipype.interfaces.bru2nii.Bru2
Failed example:
    converter.inputs.input_dir = "brukerdir"
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.interfaces.bru2nii.Bru2[2]>", line 1, in <module>
        converter.inputs.input_dir = "brukerdir"
      File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/traits_extension.py", line 169, in validate
        self.error(object, name, value)
      File "/usr/local/lib/python2.7/dist-packages/traits/trait_handlers.py", line 172, in error
        value )
    TraitError: The 'input_dir' trait of a Bru2InputSpec instance must be an existing directory name, but a value of 'brukerdir' <type 'str'> was specified.
----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/bru2nii.py", line 35, in nipype.interfaces.bru2nii.Bru2
Failed example:
    converter.cmdline  # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.interfaces.bru2nii.Bru2[3]>", line 1, in <module>
        converter.cmdline  # doctest: +ELLIPSIS
      File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1608, in cmdline
        self._check_mandatory_inputs()
      File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 940, in _check_mandatory_inputs
        raise ValueError(msg)
    ValueError: Bru2 requires a value for input 'input_dir'. For a list of required inputs, see Bru2.help()


----------------------------------------------------------------------
Ran 16126 tests in 92.009s

FAILED (SKIP=79, failures=1)`
