### ISSUE TITLE
Error when I try to use fsl.dti via nipype.

### ISSUE THREAD

**Issue by maxwichmann** [nipy/nipype#1703]
Dear all,

I m new to python and nipype thus I really dont know what I should do with this error message!

I want to do the fsl.dit command with nipype. I did it like it is explained on this site: http://nipy.org/nipype/interfaces/generated/nipype.interfaces.fsl.dti.html#dtifit

so this is my code

 
```
import numpy as nump

import nipype as nip

from nipype.interfaces import fsl

dti = fsl.DTIFit()

dti.inputs.dwi = '/Users/.../preprocessing/eddy_corrected_data.nii'

dti.inputs.bvecs = '/Users/.../preprocessing/bvecs'

dti.inputs.bvals = '/Users/.../preprocessing/bvals'

dti.inputs.base_name = '/.../preprocessing/DT.nii'

dti.inputs.mask = '/Users/.../preprocessing/eddy_corrected_data_brain_mask.nii'

save_tensor = '/Users/.../preprocessing/saved_tensors'
```
 

 

But I get always error messages like these:

 
```
': import numpy as nump

import nipype as nip

from nipype.interfaces import fsl

dti = fsl.DTIFit()

dti.inputs.dwi = '/Users/.../preprocessing/eddy_corrected_data.nii'

dti.inputs.bvecs = '/Users/.../preprocessing/bvecs'

dti.inputs.bvals = '/Users/.../preprocessing/bvals'

/Users/.../anaconda/lib/python3.5/site-packages/nipype/interfaces/fsl/base.py:116: UserWarning: FSL environment variables not set. setting output type to NIFTI

  warnings.warn(('FSL environment variables not set. setting output '

Traceback (most recent call last):

 

  File "<ipython-input-24-adc9fae8c5ee>", line 5, in <module>

    dti.inputs.dwi = '/Users/.../preprocessing/eddy_corrected_data.nii'

 

  File "/Users/.../anaconda/lib/python3.5/site-packages/nipype/interfaces/traits_extension.py", line 80, in validate

    self.error(object, name, value)

 

  File "/Users/.../anaconda/lib/python3.5/site-packages/traits/trait_handlers.py", line 173, in error

    value )

 

TraitError: The 'dwi' trait of a DTIFitInputSpec instance must be an existing file name, but a value of '/Users/.../preprocessing/eddy_corrected_data.nii' <class 'str'> was specified.
```
 
Maybe its because I'm using: Python 3.5.2 |Anaconda 4.2.0 (x86_64) but I dont know?
 

Thank you for any advice !

max

**Comment by oesteban** [comment]
Hi @maxwichmann, have you checked on [this](https://neurostars.org/p/4311/#4315)?

**Comment by maxwichmann** [comment]
Thanks @oesteban but this question is also from me :)) Just got another name on that website.

**Comment by mgxd** [comment]
@maxwichmann can you check that the file actually exists?

**Comment by mgxd** [comment]
closing this for now - feel free to open if you still have issues
