### ISSUE TITLE
Errors after installing nipype

### ISSUE THREAD

**Issue by robmcc10** [nipy/nipype#1801]
Hi,

I have attempted to install nipype:
conda config --add channels conda-forge
conda install nipype

The output of nipype.get_info is:
{'nibabel_version': '2.1.0', 'networkx_version': '1.11', 'numpy_version': '1.12.0', 'sys_platform': 'linux2', 'sys_version': '2.7.12 | packaged by conda-forge | (default, Sep  8 2016, 14:22:31) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]', 'commit_source': u'(none found)', 'commit_hash': u'<not found>', 'pkg_path': '/home/k1201869/.conda/envs/imaging_python2/lib/python2.7/site-packages/nipype-0.13.0rc1-py2.7.egg/nipype', 'sys_executable': '/home/k1201869/.conda/envs/imaging_python2/bin/python', 'traits_version': '4.6.0', 'scipy_version': '0.18.1'}

When I have then checked the install:
python -c "import nipype; nipype.test()"

I receive the the errors below. I would be most grateful if anyone could suggest where I am going wrong.

Many thanks,

Rob

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nipype/pipeline/plugins/tests/test_base.py", line 9, in <module>
    import mock
ImportError: No module named mock

======================================================================
FAIL: Doctest: nipype.interfaces.bru2nii.Bru2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for nipype.interfaces.bru2nii.Bru2
  File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nipype/interfaces/bru2nii.py", line 26, in Bru2

----------------------------------------------------------------------
File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nipype/interfaces/bru2nii.py", line 34, in nipype.interfaces.bru2nii.Bru2
Failed example:
    converter.inputs.input_dir = "brukerdir"
Exception raised:
    Traceback (most recent call last):
      File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.interfaces.bru2nii.Bru2[2]>", line 1, in <module>
        converter.inputs.input_dir = "brukerdir"
      File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nipype/interfaces/traits_extension.py", line 169, in validate
        self.error(object, name, value)
      File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
        value )
    TraitError: The 'input_dir' trait of a Bru2InputSpec instance must be an existing directory name, but a value of 'brukerdir' <type 'str'> was specified.
----------------------------------------------------------------------
File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nipype/interfaces/bru2nii.py", line 35, in nipype.interfaces.bru2nii.Bru2
Failed example:
    converter.cmdline  # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.interfaces.bru2nii.Bru2[3]>", line 1, in <module>
        converter.cmdline  # doctest: +ELLIPSIS
      File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1608, in cmdline
        self._check_mandatory_inputs()
      File "/home/k1201869/.conda/envs/imaging.python2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 940, in _check_mandatory_inputs
        raise ValueError(msg)
    ValueError: Bru2 requires a value for input 'input_dir'. For a list of required inputs, see Bru2.help()

----------------------------------------------------------------------
Ran 17278 tests in 219.298s

FAILED (SKIP=27, errors=1, failures=1)

**Comment by mgxd** [comment]
Hi Rob,

This may be an issue with the version on conda - could you try updating to the current master?

**Comment by ariekahn** [comment]
Hi Rob,

There are a few additional packages that are needed to run the tests but aren't normally going to get installed by conda, `mock` included. I believe they only get pulled in when `python setup.py test` is run?

**Comment by mgxd** [comment]
@robmcc10 have you been able to fix this issue?

**Comment by robmcc10** [comment]
Hi mgxd,

I have not yet fixed it as unable to update conda currently. I will try and install again at a later date. So please feel free to mark the issue closed and I will ask again if there are any problems when I try and install in future.

Best Wishes

Rob
