### ISSUE TITLE
Failure on MRTrix2TrackVis with nipype 0.13 but not the older 0.12

### ISSUE THREAD

**Issue by dorianps** [nipy/nipype#1802]
### Summary
The same code fails if I use the developer version of nipype 0.13 but works with the older release 0.12.
Sorry for not giving too much details, it's my first time using nipype and I did not keep track of everything (who would have thought that it was the nipype version).

### Actual behavior
The ".trk" file produce with the new version is 1kb with nothing in it. It loads in TrackVis but has not streamlines to show.

### Expected behavior
The ".trk" file should be dependent on the number of streamlines, and larger than 1kb. It should also be loadable in TrackVis.

### How to replicate the behavior
```import nipype.interfaces.mrtrix as mrt
tck2trk = mrt.MRTrix2TrackVis()
tck2trk.inputs.in_file = 'temp.tck'
tck2trk.inputs.image_file = 'meanb0.nii.gz'
tck2trk.inputs.out_filename = 'temp.trk'
tck2trk.run()
```

### Platform details:
please paste the output of: `python -c "import nipype; print(nipype.get_info())"`
This is what's working well.
{'nibabel_version': '2.1.0', 'networkx_version': '1.11', 'numpy_version': '1.12.0', 'sys_platform': 'linux2', 'sys_version': '2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'commit_source': 'installation', 'commit_hash': u'a4d1e07', 'pkg_path': '/data/jag/dpustina/engine/anaconda/lib/python2.7/site-packages/nipype', 'sys_executable': '/data/jag/dpustina/engine/anaconda/bin/python', 'traits_version': '4.6.0', 'scipy_version': '0.18.1'}

I am trying to upload a zip file to help you replicate the error but it's not allowing it.

**Comment by mgxd** [comment]
Hi @dorianps,
This seems weird, if you could share some data with me to replicate this I'd like to take a look

**Comment by dorianps** [comment]
Follow up: I have installed nipype in 3-4 computers in the last two days, and I finally realized that all packages need to be updated for the Trackvis conversion to work. That said, once everything works on nipype 0.12.1 upgrading to 0.13 brings a charset error, as below.

Files can be located here (rar file): https://www.wetransfer.com/downloads/0b7d2283bc6ce3f5e26d6774d9d3274e20170209031546/0e81ee06f00c6dca76fb3839aa98861720170209031546/b34e3b
```
Python 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import nipype.interfaces.mrtrix as mrt
tck2trk = mrt.MRTrix2TrackVis()
tck2trk.inputs.in_file = 'LeftTempSingleSeed_tracks.tck'
tck2trk.inputs.image_file = 'meanb0.nii.gz'
tck2trk.inputs.out_filename = 'LeftTempSingleSeed_tracks.trk'
tck2trk.run()  >>> tck2trk = mrt.MRTrix2TrackVis()
>>> tck2trk.inputs.in_file = 'LeftTempSingleSeed_tracks.tck'
>>> tck2trk.inputs.image_file = 'meanb0.nii.gz'
>>> tck2trk.inputs.out_filename = 'LeftTempSingleSeed_tracks.trk'
>>> tck2trk.run()
170208-22:07:13,340 interface INFO:
         Reading header data...
170208-22:07:13,340 interface INFO:
         ...adding "3" to header for key "downsample_factor"
170208-22:07:13,340 interface INFO:
         ...adding "0.25" to header for key "fod_power"
170208-22:07:13,340 interface INFO:
         ...adding "0.100000001" to header for key "init_threshold"
170208-22:07:13,340 interface INFO:
         ...adding "8" to header for key "lmax"
170208-22:07:13,340 interface INFO:
         ...adding "60" to header for key "max_angle"
170208-22:07:13,340 interface INFO:
         ...adding "243.00621" to header for key "max_dist"
170208-22:07:13,340 interface INFO:
         ...adding "200000" to header for key "max_num_attempts"
170208-22:07:13,340 interface INFO:
         ...adding "2000" to header for key "max_num_tracks"
170208-22:07:13,340 interface INFO:
         ...adding "1" to header for key "max_seed_attempts"
170208-22:07:13,340 interface INFO:
         ...adding "1000" to header for key "max_trials"
170208-22:07:13,340 interface INFO:
         ...adding "iFOD2" to header for key "method"
170208-22:07:13,340 interface INFO:
         ...adding "12.1503105" to header for key "min_dist"
170208-22:07:13,340 interface INFO:
         ...adding "0.3.15-285-g68589079" to header for key "mrtrix_version"
170208-22:07:13,340 interface INFO:
         ...adding "1" to header for key "output_step_size"
170208-22:07:13,340 interface INFO:
         ...adding "0" to header for key "rk4"
170208-22:07:13,340 interface INFO:
         ...adding "4" to header for key "samples_per_step"
170208-22:07:13,340 interface INFO:
         ...adding "1" to header for key "sh_precomputed"
170208-22:07:13,340 interface INFO:
         ...adding "WMfod.mif" to header for key "source"
170208-22:07:13,340 interface INFO:
         ...adding "1" to header for key "step_size"
170208-22:07:13,340 interface INFO:
         ...adding "0" to header for key "stop_on_all_include"
170208-22:07:13,340 interface INFO:
         ...adding "0.100000001" to header for key "threshold"
170208-22:07:13,340 interface INFO:
         ...adding "1486486988.2982976437" to header for key "timestamp"
170208-22:07:13,340 interface INFO:
         ...adding "0" to header for key "unidirectional"
170208-22:07:13,340 interface INFO:
         ...adding "seed LeftTempSingleSeed.mif" to header for key "roi"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/fajtori/Desktop/localmrtrixHCP/src/nipype/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/mnt/c/Users/fajtori/Desktop/localmrtrixHCP/src/nipype/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/mnt/c/Users/fajtori/Desktop/localmrtrixHCP/src/nipype/nipype/interfaces/mrtrix/convert.py", line 190, in _run_interface
    header, streamlines = read_mrtrix_tracks(self.inputs.in_file, as_generator=True)
  File "/mnt/c/Users/fajtori/Desktop/localmrtrixHCP/src/nipype/nipype/interfaces/mrtrix/convert.py", line 52, in read_mrtrix_tracks
    header = read_mrtrix_header(in_file)
  File "/mnt/c/Users/fajtori/Desktop/localmrtrixHCP/src/nipype/nipype/interfaces/mrtrix/convert.py", line 61, in read_mrtrix_header
    for line in fileobj:
  File "/home/dp/anaconda2/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf5 in position 128: invalid start byte
```
Rolling back to 0.12 fixes the conversion, everything works fine again:

```
dp@EDITING:/mnt/c/Users/fajtori/Desktop/localmtrtrix$ pip uninstall nipype
Uninstalling nipype-0.13.0-g61978ad.dev:
  /home/dp/anaconda2/bin/nipypecli
  /home/dp/anaconda2/lib/python2.7/site-packages/nipype.egg-link
Proceed (y/n)? y
  Successfully uninstalled nipype-0.13.0-g61978ad.dev
dp@EDITING:/mnt/c/Users/fajtori/Desktop/localmtrtrix$ pip install nipype
Collecting nipype
  Using cached nipype-0.12.1-py2.py3-none-any.whl
Requirement already satisfied: mock in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: nibabel>=2.0.1 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: python-dateutil>=1.5 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: simplejson>=3.8.0 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: future>=0.15.2 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: scipy>=0.11 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: numpy>=1.6.2 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: nose>=1.2 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: networkx>=1.7 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: xvfbwrapper in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: traits>=4.3 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: prov>=1.4.0 in /home/dp/anaconda2/lib/python2.7/site-packages (from nipype)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /home/dp/anaconda2/lib/python2.7/site-packages (from mock->nipype)
Requirement already satisfied: six>=1.9 in /home/dp/anaconda2/lib/python2.7/site-packages (from mock->nipype)
Requirement already satisfied: pbr>=0.11 in /home/dp/anaconda2/lib/python2.7/site-packages (from mock->nipype)
Requirement already satisfied: decorator>=3.4.0 in /home/dp/anaconda2/lib/python2.7/site-packages (from networkx>=1.7->nipype)
Requirement already satisfied: lxml in /home/dp/anaconda2/lib/python2.7/site-packages (from prov>=1.4.0->nipype)
Requirement already satisfied: rdflib>=4.2.1 in /home/dp/anaconda2/lib/python2.7/site-packages (from prov>=1.4.0->nipype)
Requirement already satisfied: isodate in /home/dp/anaconda2/lib/python2.7/site-packages (from rdflib>=4.2.1->prov>=1.4.0->nipype)
Requirement already satisfied: pyparsing in /home/dp/anaconda2/lib/python2.7/site-packages (from rdflib>=4.2.1->prov>=1.4.0->nipype)
Installing collected packages: nipype
Successfully installed nipype-0.12.1
dp@EDITING:/mnt/c/Users/fajtori/Desktop/localmtrtrix$ ^C
dp@EDITING:/mnt/c/Users/fajtori/Desktop/localmtrtrix$ python
Python 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import nipype.interfaces.mrtrix as mrt
tck2trk = mrt.MRTrix2TrackVis()
tck2trk.inputs.in_file = 'LeftTempSingleSeed_tracks.tck'
tck2trk.inputs.image_file = 'meanb0.nii.gz'
tck2trk.inputs.out_filename = 'LeftTempSingleSeed_tracks.trk'
tck2trk.run()  >>> tck2trk = mrt.MRTrix2TrackVis()
>>> tck2trk.inputs.in_file = 'LeftTempSingleSeed_tracks.tck'
>>> tck2trk.inputs.image_file = 'meanb0.nii.gz'
>>> tck2trk.inputs.out_filename = 'LeftTempSingleSeed_tracks.trk'
>>> tck2trk.run()
170208-22:09:14,793 interface INFO:
         Reading header data...
170208-22:09:14,793 interface INFO:
         ...adding "3" to header for key "downsample_factor"
170208-22:09:14,793 interface INFO:
         ...adding "0.25" to header for key "fod_power"
170208-22:09:14,793 interface INFO:
         ...adding "0.100000001" to header for key "init_threshold"
170208-22:09:14,793 interface INFO:
         ...adding "8" to header for key "lmax"
170208-22:09:14,793 interface INFO:
         ...adding "60" to header for key "max_angle"
170208-22:09:14,793 interface INFO:
         ...adding "243.00621" to header for key "max_dist"
170208-22:09:14,793 interface INFO:
         ...adding "200000" to header for key "max_num_attempts"
170208-22:09:14,793 interface INFO:
         ...adding "2000" to header for key "max_num_tracks"
170208-22:09:14,793 interface INFO:
         ...adding "1" to header for key "max_seed_attempts"
170208-22:09:14,793 interface INFO:
         ...adding "1000" to header for key "max_trials"
170208-22:09:14,793 interface INFO:
         ...adding "iFOD2" to header for key "method"
170208-22:09:14,793 interface INFO:
         ...adding "12.1503105" to header for key "min_dist"
170208-22:09:14,793 interface INFO:
         ...adding "0.3.15-285-g68589079" to header for key "mrtrix_version"
170208-22:09:14,793 interface INFO:
         ...adding "1" to header for key "output_step_size"
170208-22:09:14,793 interface INFO:
         ...adding "0" to header for key "rk4"
170208-22:09:14,793 interface INFO:
         ...adding "4" to header for key "samples_per_step"
170208-22:09:14,793 interface INFO:
         ...adding "1" to header for key "sh_precomputed"
170208-22:09:14,793 interface INFO:
         ...adding "WMfod.mif" to header for key "source"
170208-22:09:14,793 interface INFO:
         ...adding "1" to header for key "step_size"
170208-22:09:14,793 interface INFO:
         ...adding "0" to header for key "stop_on_all_include"
170208-22:09:14,793 interface INFO:
         ...adding "0.100000001" to header for key "threshold"
170208-22:09:14,793 interface INFO:
         ...adding "1486486988.2982976437" to header for key "timestamp"
170208-22:09:14,793 interface INFO:
         ...adding "0" to header for key "unidirectional"
170208-22:09:14,793 interface INFO:
         ...adding "seed LeftTempSingleSeed.mif" to header for key "roi"
170208-22:09:14,793 interface INFO:
         ...adding "mask bmask.nii.gz" to header for key "roi"
170208-22:09:14,793 interface INFO:
         ...adding "mask bmask.nii.gz" to header for key "roi"
170208-22:09:14,793 interface INFO:
         ...adding "Float32LE" to header for key "datatype"
170208-22:09:14,793 interface INFO:
         ...adding ". 640" to header for key "file"
170208-22:09:14,793 interface INFO:
         ...adding "2000" to header for key "count"
170208-22:09:14,793 interface INFO:
         ...adding "2925" to header for key "total_count"
170208-22:09:14,793 interface INFO:
         Reached the end of the header!
170208-22:09:14,793 interface INFO:
         Identifying the number of points per tract...
170208-22:09:14,809 interface INFO:
         MRTrix Header:
170208-22:09:14,809 interface INFO:
         {'roi': 'mask bmask.nii.gz', 'mrtrix_version': '0.3.15-285-g68589079', 'max_dist': '243.00621', 'file': '. 640', 'threshold': '0.100000001',
'output_step_size': '1', 'max_num_attempts': '200000', 'downsample_factor': '3', 'source': 'WMfod.mif', 'step_size': '1', 'method': 'iFOD2', 'rk4': '0
', 'min_dist': '12.1503105', 'init_threshold': '0.100000001', 'timestamp': '1486486988.2982976437', 'samples_per_step': '4', 'offset': 640, 'fod_power
': '0.25', 'stop_on_all_include': '0', 'max_angle': '60', 'count': 2000, 'max_seed_attempts': '1', 'max_num_tracks': '2000', 'sh_precomputed': '1', 't
otal_count': '2925', 'max_trials': '1000', 'datatype': 'Float32LE', 'lmax': '8', 'unidirectional': '0'}
170208-22:09:14,809 interface INFO:
         Applying transformation from scanner coordinates to meanb0.nii.gz
170208-22:09:14,809 interface INFO:
         Reading tracks...
170208-22:09:14,809 interface INFO:
         1% : 20 tracks read
170208-22:09:14,809 interface INFO:
         2% : 40 tracks read
170208-22:09:14,809 interface INFO:
         3% : 60 tracks read
170208-22:09:14,809 interface INFO:
         4% : 80 tracks read
170208-22:09:14,809 interface INFO:
         5% : 100 tracks read
170208-22:09:14,824 interface INFO:
         6% : 120 tracks read
170208-22:09:14,824 interface INFO:
         7% : 140 tracks read
170208-22:09:14,824 interface INFO:
         8% : 160 tracks read
170208-22:09:14,824 interface INFO:
         9% : 180 tracks read
170208-22:09:14,824 interface INFO:
         10% : 200 tracks read
170208-22:09:14,824 interface INFO:
         11% : 220 tracks read
170208-22:09:14,824 interface INFO:
         12% : 240 tracks read
170208-22:09:14,824 interface INFO:
         13% : 260 tracks read
170208-22:09:14,824 interface INFO:
         14% : 280 tracks read
170208-22:09:14,824 interface INFO:
         15% : 300 tracks read
170208-22:09:14,824 interface INFO:
         16% : 320 tracks read
170208-22:09:14,840 interface INFO:
         17% : 340 tracks read
170208-22:09:14,840 interface INFO:
         18% : 360 tracks read
170208-22:09:14,840 interface INFO:
         19% : 380 tracks read
170208-22:09:14,840 interface INFO:
         20% : 400 tracks read
170208-22:09:14,840 interface INFO:
         21% : 420 tracks read
170208-22:09:14,840 interface INFO:
         22% : 440 tracks read
170208-22:09:14,840 interface INFO:
         23% : 460 tracks read
170208-22:09:14,840 interface INFO:
         24% : 480 tracks read
170208-22:09:14,840 interface INFO:
         25% : 500 tracks read
170208-22:09:14,840 interface INFO:
         26% : 520 tracks read
170208-22:09:14,856 interface INFO:
         27% : 540 tracks read
170208-22:09:14,856 interface INFO:
         28% : 560 tracks read
170208-22:09:14,856 interface INFO:
         28% : 580 tracks read
170208-22:09:14,856 interface INFO:
         30% : 600 tracks read
170208-22:09:14,856 interface INFO:
         31% : 620 tracks read
170208-22:09:14,856 interface INFO:
         32% : 640 tracks read
170208-22:09:14,856 interface INFO:
         33% : 660 tracks read
170208-22:09:14,856 interface INFO:
         34% : 680 tracks read
170208-22:09:14,856 interface INFO:
         35% : 700 tracks read
170208-22:09:14,856 interface INFO:
         36% : 720 tracks read
170208-22:09:14,871 interface INFO:
         37% : 740 tracks read
170208-22:09:14,871 interface INFO:
         38% : 760 tracks read
170208-22:09:14,871 interface INFO:
         39% : 780 tracks read
170208-22:09:14,871 interface INFO:
         40% : 800 tracks read
170208-22:09:14,871 interface INFO:
         41% : 820 tracks read
170208-22:09:14,871 interface INFO:
         42% : 840 tracks read
170208-22:09:14,871 interface INFO:
         43% : 860 tracks read
170208-22:09:14,871 interface INFO:
         44% : 880 tracks read
170208-22:09:14,871 interface INFO:
         45% : 900 tracks read
170208-22:09:14,871 interface INFO:
         46% : 920 tracks read
170208-22:09:14,871 interface INFO:
         47% : 940 tracks read
170208-22:09:14,887 interface INFO:
         48% : 960 tracks read
170208-22:09:14,887 interface INFO:
         49% : 980 tracks read
170208-22:09:14,887 interface INFO:
         50% : 1000 tracks read
170208-22:09:14,887 interface INFO:
         51% : 1020 tracks read
170208-22:09:14,887 interface INFO:
         52% : 1040 tracks read
170208-22:09:14,887 interface INFO:
         53% : 1060 tracks read
170208-22:09:14,887 interface INFO:
         54% : 1080 tracks read
170208-22:09:14,887 interface INFO:
         55% : 1100 tracks read
170208-22:09:14,887 interface INFO:
         56% : 1120 tracks read
170208-22:09:14,887 interface INFO:
         56% : 1140 tracks read
170208-22:09:14,887 interface INFO:
         57% : 1160 tracks read
170208-22:09:14,887 interface INFO:
         59% : 1180 tracks read
170208-22:09:14,902 interface INFO:
         60% : 1200 tracks read
170208-22:09:14,902 interface INFO:
         61% : 1220 tracks read
170208-22:09:14,902 interface INFO:
         62% : 1240 tracks read
170208-22:09:14,902 interface INFO:
         63% : 1260 tracks read
170208-22:09:14,902 interface INFO:
         64% : 1280 tracks read
170208-22:09:14,902 interface INFO:
         65% : 1300 tracks read
170208-22:09:14,902 interface INFO:
         66% : 1320 tracks read
170208-22:09:14,902 interface INFO:
         67% : 1340 tracks read
170208-22:09:14,902 interface INFO:
         68% : 1360 tracks read
170208-22:09:14,902 interface INFO:
         69% : 1380 tracks read
170208-22:09:14,918 interface INFO:
         70% : 1400 tracks read
170208-22:09:14,918 interface INFO:
         71% : 1420 tracks read
170208-22:09:14,918 interface INFO:
         72% : 1440 tracks read
170208-22:09:14,918 interface INFO:
         73% : 1460 tracks read
170208-22:09:14,918 interface INFO:
         74% : 1480 tracks read
170208-22:09:14,918 interface INFO:
         75% : 1500 tracks read
170208-22:09:14,918 interface INFO:
         76% : 1520 tracks read
170208-22:09:14,918 interface INFO:
         77% : 1540 tracks read
170208-22:09:14,918 interface INFO:
         78% : 1560 tracks read
170208-22:09:14,918 interface INFO:
         79% : 1580 tracks read
170208-22:09:14,918 interface INFO:
         80% : 1600 tracks read
170208-22:09:14,918 interface INFO:
         81% : 1620 tracks read
170208-22:09:14,934 interface INFO:
         82% : 1640 tracks read
170208-22:09:14,934 interface INFO:
         83% : 1660 tracks read
170208-22:09:14,934 interface INFO:
         84% : 1680 tracks read
170208-22:09:14,934 interface INFO:
         85% : 1700 tracks read
170208-22:09:14,934 interface INFO:
         86% : 1720 tracks read
170208-22:09:14,934 interface INFO:
         87% : 1740 tracks read
170208-22:09:14,934 interface INFO:
         88% : 1760 tracks read
170208-22:09:14,934 interface INFO:
         89% : 1780 tracks read
170208-22:09:14,934 interface INFO:
         90% : 1800 tracks read
170208-22:09:14,934 interface INFO:
         91% : 1820 tracks read
170208-22:09:14,934 interface INFO:
         92% : 1840 tracks read
170208-22:09:14,949 interface INFO:
         93% : 1860 tracks read
170208-22:09:14,949 interface INFO:
         94% : 1880 tracks read
170208-22:09:14,949 interface INFO:
         95% : 1900 tracks read
170208-22:09:14,949 interface INFO:
         96% : 1920 tracks read
170208-22:09:14,949 interface INFO:
         97% : 1940 tracks read
170208-22:09:14,949 interface INFO:
         98% : 1960 tracks read
170208-22:09:14,949 interface INFO:
         99% : 1980 tracks read
170208-22:09:14,949 interface INFO:
         100% : 2000 tracks read
170208-22:09:14,949 interface INFO:
         Saving Trackvis file as /mnt/c/Users/fajtori/Desktop/localmtrtrix/LeftTempSingleSeed_tracks.trk
170208-22:09:14,949 interface INFO:
         TrackVis Header:
170208-22:09:14,949 interface INFO:
         ('TRACK', [96, 96, 52], [ 2.39582992,  2.39582992,  2.5       ], [ 0.,  0.,  0.], 0, ['', '', '', '', '', '', '', '', '', ''], 0, ['', '', ''
, '', '', '', '', '', '', ''], [[ -2.38634968e+00,  -4.16538902e-02,  -2.17889369e-01,   1.19886192e+02], [ -5.98501377e-02,   2.38603210e+00,   2.170
60238e-01,  -1.19028839e+02], [ -2.04339847e-01,  -2.12408915e-01,   2.48100972e+00,  -1.34701786e+01], [  0.00000000e+00,   0.00000000e+00,   0.00000
000e+00,   1.00000000e+00]], '', 'LAS', '', [ 0.,  0.,  0.,  0.,  0.,  0.], '', '', '', '', '', '', '', 2000, 2, 1000)
<nipype.interfaces.base.InterfaceResult object at 0x7fa1eaab97d0>
```

**Comment by mgxd** [comment]
@dorianps thanks for the info - i've submitted a patch for this that ignores the problem. This seemed to have been caused from switching over to unicode encoding.

**Comment by satra** [comment]
@dorianps - can you verify the fix from mathias' branch?
