### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by robmcc10** [nipy/nipype#1860]
### Summary
Dear All,

I have a pipeline that is designed to extract the proportion of CSF from a MRS voxel. The script was designed for a GE scanner so the inputs are the structural T1 image and the MRS .7 file. I have been trying to modify the script to work with data obtained on a Philips scanner. 

As a first step I have amended the script to not depend on the MRS file (i.e. I enter the MRS voxel coordinates manually). I have run into a problem that seems to be related to difference between the T1 images that I have acquired on the philips scanner and those acquired on the GE scanner. When I run the script with a GE acquired T1 image the script runs without a problem but when I run it with a Philips T1 I get the error pasted below. I would be most grateful if anyone was able to offer any advice.

Many thanks,

Rob

170303-16:47:15,737 workflow ERROR:
	 ['Node extract_proportions.a0 failed to run on host nanlnx17.iop.kcl.ac.uk.']
170303-16:47:15,738 workflow INFO:
	 Saving crash info to /home/k1201869/coding/MRS_scripts/crash-20170303-164715-k1201869-extract_proportions.a0-c1780cbe-1767-4128-831a-3995ced2647e.pklz
170303-16:47:15,738 workflow INFO:
	 Traceback (most recent call last): 
 File "/home/k1201869/MRS_STEINER/voxelextract_test2/workingdir_voxel_extract/reset/batch/pyscript_20170303_164615_reset_extract_proportions.a0.py", line 32, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 499, in _run_interface
    out = function_handle(**args)
  File "<string>", line 91, in extract_proportions
IndexError: index 0 is out of bounds for axis 0 with size 0
Interface Function failed to run. 

170303-16:48:15,826 workflow INFO:
	 ***********************************
170303-16:48:15,827 workflow ERROR:
	 could not run node: reset.extract_proportions.a0
170303-16:48:15,827 workflow INFO:
	 crashfile: /home/k1201869/coding/MRS_scripts/crash-20170303-164715-k1201869-extract_proportions.a0-c1780cbe-1767-4128-831a-3995ced2647e.pklz
170303-16:48:15,827 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "voxel_extract.py", line 226, in <module>
    voxel_extract.run(plugin='SGE', plugin_args={'max_jobs': 30, 'qsub_args': '-q rhe5b'})
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 597, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 274, in run
    report_nodes_not_run(notrun)
  File "/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 95, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

### Platform details:
{'nibabel_version': '2.1.0', 'networkx_version': '1.11', 'numpy_version': '1.11.3', 'sys_platform': 'linux2', 'sys_version': '2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'commit_source': 'installation', 'commit_hash': u'a4d1e07', 'pkg_path': '/home/k1201869/anaconda2/lib/python2.7/site-packages/nipype', 'sys_executable': '/home/k1201869/anaconda2/bin/python', 'traits_version': '4.6.0', 'scipy_version': '0.18.1'}
0.12.1

**Comment by oesteban** [comment]
It looks like a `Function` node failing, so you would need to figure out what is happening there. Likely you are trying to access an empty array.

More detailed information about the node can be extracted running: 
```
nipypecli crash /home/k1201869/coding/MRS_scripts/crash-20170303-164715-k1201869-extract_proportions.a0-c1780cbe-1767-4128-831a-3995ced2647e.pklz
```

**Comment by mgxd** [comment]
@robmcc10 have you solved the problem? If not, please post the output of the command @oesteban    included above

**Comment by mgxd** [comment]
@robmcc10 feel free to open this again if needed
