### ISSUE TITLE
Pickle/str/bytes error in Workflow.export() on Python 3

### ISSUE THREAD

**Issue by ashgillman** [nipy/nipype#1996]
### Summary
Workflow.export() (exporting a workflow to Python code) fails in Python3

```
Traceback (most recent call last):
  File "moco_pipeline_057A_5min_drag.py", line 67, in <module>
    att_cor=True)
  File "/home/gil2a4/proj/pylx/pylx/workflows/pet/moco.py", line 1315, in create_mcir_ants_workflow
    iterfield=('transforms', 'invert_flags'))
  File "/home/gil2a4/proj/pylx/pylx/workflows/pet/moco.py", line 1596, in map_workflow
    make_wf_fun = workflow.export(prefix='/tmp/', include_config=True)
  File "/nix/store/1540y02drlhbvva09i7kp7ww6f5lhd8d-python3.4-nipype-0.13.0-rc1-my-changes/lib/python3.4/site-packages/nipype/pipeli
ne/engine/workflows.py", line 494, in export
    include_config=include_config)
  File "/nix/store/1540y02drlhbvva09i7kp7ww6f5lhd8d-python3.4-nipype-0.13.0-rc1-my-changes/lib/python3.4/site-packages/nipype/pipeli
ne/engine/utils.py", line 154, in format_node
    lines.extend(_write_inputs(node))
  File "/nix/store/1540y02drlhbvva09i7kp7ww6f5lhd8d-python3.4-nipype-0.13.0-rc1-my-changes/lib/python3.4/site-packages/nipype/pipeli
ne/engine/utils.py", line 99, in _write_inputs
    lines.append(pickle.loads(val))
TypeError: 'str' does not support the buffer interface
```

Here is the offending function:

nipype/nipype/pipeline/engine/utils.py

```py
 85     def _write_inputs(node):
 86         lines = []
 87         nodename = node.fullname.replace('.', '_')
 88         for key, _ in list(node.inputs.items()):
 89             val = getattr(node.inputs, key)
 90             if isdefined(val):
 91                 if type(val) == str:
 92                     try:
 93                         func = create_function_from_source(val)
 94                     except RuntimeError as e:
 95                         lines.append("%s.inputs.%s = '%s'" % (nodename, key, val))
 96                     else:
 97                         funcname = [name for name in func.__globals__
 98                                     if name != '__builtins__'][0]
 99  ->                     lines.append(pickle.loads(val))
100                         if funcname == nodename:
101                             lines[-1] = lines[-1].replace(' %s(' % funcname,
102                                                           ' %s_1(' % funcname)
103                             funcname = '%s_1' % funcname
104                         lines.append('from nipype.utils.misc import getsource')
105                         lines.append("%s.inputs.%s = getsource(%s)" % (nodename,
106                                                                        key,
107                                                                        funcname))
108                 else:
109                     lines.append('%s.inputs.%s = %s' % (nodename, key, val))
110         return lines
```

The direct error is due to val being a `str`, when pickle.loads expects a `bytes`. However, encoding the string does not fix the error:

```py
pickle.loads(val.encode('ascii'))
*** _pickle.UnpicklingError: could not find MARK
```

The Node in question is a Function node, and the particular failing key is `function_str`. I am not sure why every string is `pickle.loads`ed?

### How to replicate the behavior
Untested

### Platform details:

Python 3, a patched version of 0.13.0-rc1

### Possible solution:
```py
def _write_inputs(node):
    lines = []
    nodename = node.fullname.replace('.', '_')
    for key, _ in list(node.inputs.items()):
        val = getattr(node.inputs, key)
        if isdefined(val):
            if type(val) == str:
                try:
                    func = create_function_from_source(val)
                except RuntimeError as e:
                    lines.append("%s.inputs.%s = '%s'" % (nodename, key, val))
                else:
                    funcname = [name for name in func.__globals__
                                if name != '__builtins__'][0]
                    try:
                        lines.append(pickle.loads(val.encode('ascii')))
                    except pickle.UnpicklingError:
                        # might be plain formatted
                        lines.append(val)
                    if funcname == nodename:
                        lines[-1] = lines[-1].replace(' %s(' % funcname,
                                                      ' %s_1(' % funcname)
                        funcname = '%s_1' % funcname
                    lines.append('from nipype.utils.misc import getsource')
                    lines.append("%s.inputs.%s = getsource(%s)" % (nodename,
                                                                  key,
                                                                  funcname))
            else:
                lines.append('%s.inputs.%s = %s' % (nodename, key, val))
    return lines
```

Use str.encode(), but on failure, insert the string verbatim.

**Comment by satra** [comment]
@ashgillman - every workflow function node would write this file. i'm not sure what is it about your function that's causing this error. could you create a test file that we could run with just the function node in question?

**Comment by ashgillman** [comment]
Sure, I'll have a look over the weekend.

I am trying to do a few non-standard things (wrapping Workflows in Function Nodes so I can map over them), so perhaps this is related (I thought originally maybe not).

Unrelated, but if you have a solution for mapping a Workflow over a list (length is unknown until runtime, so can't use iterables) I'd love to hear.

**Comment by mgxd** [comment]
@ashgillman is this still an issue?

**Comment by ashgillman** [comment]
@mgxd
I believe it may be, but I cannot find the example code (I must have gotten busy that weekend I referred to in my last message).

I propose closing this issue, as I have not sun into this since
