### ISSUE TITLE
MergeNifti throwing error

### ISSUE THREAD

**Issue by jmschabdach** [nipy/nipype#2021]
### Summary

I'm encountering an error when trying to run the MergeNifti on a series of nii.gz images. 

### Expected behavior

I expected this code to combine the images in the list into a single .nii.gz file and save it.

### How to replicate the behavior

The code I'm using is pretty simple:

```
from nipype.interfaces import dcmstack

niftiMerger = dcmstack.MergeNifti()
niftiMerger.inputs.in_files = [000.nii.gz, 001.nii.gz, 002.nii.gz, 003.nii.gz, 004.nii.gz, 005.nii.gz
niftiMerger.inputs.out_path = 'registration_combined'
niftiMerger.run()
```

### Actual behavior

The error occurs on `niftiMerger.run()`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/nipype/interfaces/dcmstack.py", line 364, in _run_interface
    for nii in niis
NameError: global name 'NiftiWrapper' is not defined
Interface MergeNifti failed to run.
```

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

When I run this command, I get another error: 

```
 $ python -c "import nipype; print nipype.get_info()"Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/nipype/__init__.py", line 60, in <lambda>
    get_info = lambda: _get_pkg_info(os.path.dirname(__file__))
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/nipype/pkg_info.py", line 82, in get_pkg_info
    src, hsh = pkg_commit_hash(pkg_path)
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/nipype/pkg_info.py", line 52, in pkg_commit_hash
    archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/backports/configparser/__init__.py", line 811, in get
    d)
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/backports/configparser/__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/backports/configparser/__init__.py", line 434, in _interpolate_some
    "found: %r" % (rest,))
backports.configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'
```

Package path: '/home/jenna/anaconda2/envs/chp-pirc/lib/python2.7/site-packages/nipype'
Nipype version: 0.12.1
Sys version: 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Sys executable: /home/jenna/anaconda2/envs/chp-pirc/bin/python
Sys platform: linux2

The versions of the relevant libraries are
- numpy: 1.12.1
- scipy: 0.19.0
- networkx_version: 1.11
- nibabel_version: 2.1.0
- traits_version: 4.6.0

The only platform information I didn't get were the commit source and the commit hash.

I was able to duplicate this error on another computer, also linux with 

Package path: /usr/local/lib/python2.7/dist-packages/nipype
Nipype version: 0.12.1
Sys version: 2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]
Sys executable: /usr/bin/python
Sys platform: linux2
Commit source: installation
Commit hash: a4d1e07

The versions of the relevant libraries are
- numpy: 1.8.2
- scipy: 0.13.3
- networkx_version: 1.8.1
- nibabel_version: 2.0.2
- traits_version: 4.1.0

Any help and suggestions you can offer would be greatly appreciated.

**Comment by effigies** [comment]
This looks like it should only happen if [dcmstack](https://github.com/moloney/dcmstack) is not installed. If you're on NeuroDebian, you can install it with `apt-get install python-dcmstack`.

If that ends up being a problem, I think pretty much every package has something to do this, such as [`fslmerge`](https://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.fsl/utils.html#merge), or [`mri_concat`](https://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.freesurfer/model.html#concatenate).

**Comment by jmschabdach** [comment]
Installing `python-dcmstack` definitely helped, though now I'm getting another error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/dcmstack.py", line 364, in _run_interface
    for nii in niis
  File "/usr/lib/python2.7/dist-packages/dcmstack/dcmmeta.py", line 1270, in __init__
    self.meta_ext.check_valid()
  File "/usr/lib/python2.7/dist-packages/dcmstack/dcmmeta.py", line 305, in check_valid
    'classification %s' % classes[0])
dcmstack.dcmmeta.InvalidExtensionError: The extension is not valid: Missing required base classification time
```

Initial Google searches have not been helpful in resolving this error.

**Comment by effigies** [comment]
Are you using NIfTIs created by dcmstack? I think (I've never used it) the issue is that it's expecting DICOM-derived header data to be available, and it can't find it.

**Comment by jmschabdach** [comment]
Hmm. The original NIfTI file was made using Chris Rorden's `dcm2nii` utility. I used the `nipype.interfaces.ants` Registration to register each image in my list to a template image. Now I'm trying to stack the registered images. Should the header information propagate through the Registration process?

**Comment by effigies** [comment]
If you have FreeSurfer or FSL installed, you can check headers before and after with `mri_info` or `fslhd`. Otherwise, you can use nibabel:

```Python
import nibabel as nb
print(nb.load(fname).header)
```
As a first step, I might verify that the output of `dcm2nii` can be loaded with `dcmstack.NiftiWrapper` without throwing an error:

```Python
>>> from dcmstack.dcmmeta import NiftiWrapper
>>> import nibabel as nb
>>> NiftiWrapper(nb.load(orig_fname))
```

If you have that data, then we can try to figure out how to pull it through, post-registration.

**Comment by jmschabdach** [comment]
So far it looks like the output of `dcm2nii` and `dcmstack` don't play nicely together, and I believe all of my data went through `dcm2nii`. Rather than try to manhandle it to work with dcmstack, I'm going to figure out another way to combine my registered images. Thanks for all your help, @effigies!
