### ISSUE TITLE
**runtime.dictcopy())) RuntimeError: <exception str() failed>

### ISSUE THREAD

**Issue by rattar1989** [nipy/nipype#2100]
### Summary
I wrapped a matlab code and got the results like the following:

```
stty: 'standard input': Inappropriate ioctl for device
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/Wrapper/wrapper2.py", line 12, in <module>
    res = matlab.run()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1724, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/nipype/interfaces/matlab.py", line 152, in _run_interface
    self.raise_exception(runtime)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1682, in raise_exception
    **runtime.dictcopy()))
RuntimeError: <exception str() failed>

Process finished with exit code 1
```
### Expected behavior
I expect no errors because the code works correctly and the outputs are the same when I run it on matlab.

**Comment by mgxd** [comment]
@rattar1989 can you please provide the code you are running, as well as any additional information in any crashfile generated

**Comment by rattar1989** [comment]
Here is the code:
```
import nipype.pipeline.engine as pe
from nipype.interfaces.utility import Function

subjects_dir = '/home/ubuntu/matlab/MATLAB/1000231'


def data_organisation(in_path):
    import nipype.interfaces.matlab as Matlab
    matlab = Matlab.MatlabCommand()
    matlab.inputs.paths = ['/home/ubuntu/matlab/MATLAB']
    working_dir = '/home/ubuntu/matlab/data/'
    with open("/home/ubuntu/matlab/MATLAB/new/data_organization.m", "r") as src:
        script = src.read().replace("xx11233494", in_path).replace("yy11233494", working_dir)
        matlab.inputs.script = script
        matlab.run()


organization = pe.Node(Function(input_names=['in_path'], function=data_organisation),
                       name='DON')

organization.inputs.in_path = subjects_dir

organization.run()
```

It runs the the matlab script (`data_organization.m` ) and the result is correct, but I have the above-mentioned errors.

**Comment by mgxd** [comment]
can you verify `script` is correct?

and could you try running the last two lines outside of the `open()` call?

**Comment by rattar1989** [comment]
- can you verify script is correct?
There are only the following lines that have been added at the end of the `pyscript.m` file but the rest are the same as my matlab script:
```
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;
```
- and could you try running the last two lines outside of the open() call?
if you mean these lines:
```
matlab.inputs.script = script
        matlab.run()
```
the output is:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-02d858c457b5>", line 1, in <module>
    matlab.inputs.script = script
NameError: name 'script' is not defined
```
but if you mean something like the following:
```
import nipype.interfaces.matlab as Matlab
matlab = Matlab.MatlabCommand()
matlab.inputs.paths = ['/home/ubuntu/matlab/MATLAB']

with open("/home/ubuntu/matlab/MATLAB/new/data_organization.m", "r") as src:
    script = src.read()
    matlab.inputs.script = script
    res = matlab.run()
```
then the output is:
```
stty: 'standard input': Inappropriate ioctl for device
Traceback (most recent call last):
  File "/home/rahman/PycharmProjects/Wrapper/callWrapper.py", line 12, in <module>
    res = matlab.run()
  File "/home/rahman/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/home/rahman/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1724, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/rahman/anaconda2/lib/python2.7/site-packages/nipype/interfaces/matlab.py", line 152, in _run_interface
    self.raise_exception(runtime)
  File "/home/rahman/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1682, in raise_exception
    **runtime.dictcopy()))
RuntimeError: <exception str() failed>

Process finished with exit code 1
```

**Comment by mgxd** [comment]
@rattar1989 
```python
def data_organisation(in_path):
    import nipype.interfaces.matlab as Matlab
    matlab = Matlab.MatlabCommand()
    matlab.inputs.paths = ['/home/ubuntu/matlab/MATLAB']
    working_dir = '/home/ubuntu/matlab/data/'
    with open("/home/ubuntu/matlab/MATLAB/new/data_organization.m", "r") as src:
        script = src.read().replace("xx11233494", in_path).replace("yy11233494", working_dir)
    matlab.inputs.script = script
    matlab.run()
```

Did this produce a crashfile? If so, can you paste the contents?

**Comment by mgxd** [comment]
@rattar1989 if this is still an issue, feel free to reopen the issue
