### ISSUE TITLE
ANTs interfaces crash when checking version

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2127]
### Summary
ANTs interfaces crash if the version does not contain commit hash. E.g.:
```
antsRegistration --version
ANTs Version: 2.2.0
```

### Actual behavior

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1081, in run
    version=self.version)
  File "/usr/local/lib/python3.6/site-packages/nipype/interfaces/ants/base.py", line 127, in version
    return Info().version
  File "/usr/local/lib/python3.6/site-packages/nipype/interfaces/ants/base.py", line 56, in version
    v_string, githash = self._version.split('-')
ValueError: not enough values to unpack (expected 2, got 1)
```

### Expected behavior
`githash` should not be mandatory

### How to replicate the behavior
Shadow the original `antsRegistration` with a mock that just prints the above command.

### Script/Workflow details
https://github.com/poldracklab/mriqc/issues/600

### Platform details:
Unavailable. Should not be relevant.

### Execution environment
Should not be relevant.

**Comment by effigies** [comment]
Ugh. Sorry. I actually hadn't run across a released ANTs version that didn't have the githash. I'll push a fix this morning.
