### ISSUE TITLE
node function with more than one argument as input

### ISSUE THREAD

**Issue by acamargofb** [nipy/nipype#2154]
Dear Nipype users:

I am trying to create a node using a function that takes two arguments, but I don t know how to do it. I found examples with interfaces that have more than one argument but I do not find any with functions.

My code is like this:
# Example of use of the function fmri_correlation:
##P, R = fmri_correlation(path, filename_tfn, filename_rfn)

# Create Node
fmricorr = Node(Function(input_names=[path, filename_tfn, filename_rfn ],
                         output_names=["P_node", "R_node"],
                         function=fmri_correlation),
                         name='fmri_correlation_node')

**Comment by djarecka** [comment]
Here you have a simple example with Function Node that takes a function with two arguments: 

```
def add_2_arg(x_inp_1, x_inp_2):
    return x_inp_1 + x_inp_2

add = Node(Function(input_names=["x_inp_1", "x_inp_2"],
                       output_names=["val_output"],
                       function=add_2_arg),
              name='add_node')

add.inputs.x_inp_1 =4
add.inputs.x_inp_2 =3
add.run()
add.result.outputs
```

**Comment by acamargofb** [comment]
Hi Dorota:

Thanks a lot for your reply, it works the test that you send me, but there is a bug on nipype when I run a function that returns a matrix of 116x116. I sent you a sample code with the error message:

from nipype import Node, Function

def fmri_correlation2(dummy):
    import numpy as np
    p_loop = np.random.rand(116, 116)
    print('Dummy func!')
    print(p_loop.shape, type(p_loop))
    return p_loop

fmricorr = Node(Function(input_names=["dummy"],
                         output_names=["P_node"],
                         function=fmri_correlation2),
                name='fmri_correlation2_node')

fmricorr.inputs.dummy = 'test'

fmricorr.run()
print('Done')


And the traceback information is:

brain@neurodebian:~/neuro-csg-pipelines/Projects/Nipype/correlation/Python_CrossCorrelation/version2$ python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    fmricorr = Node(Function(input_names=["dummy"],
NameError: name 'Node' is not defined
brain@neurodebian:~/neuro-csg-pipelines/Projects/Nipype/correlation/Python_CrossCorrelation/version2$ python test.py
170817-14:59:01,239 workflow INFO:
     Executing node fmri_correlation2_node in dir: /tmp/tmpGm6jjh/fmri_correlation2_node
Dummy func!
((116, 116), <type 'numpy.ndarray'>)
^CTraceback (most recent call last):
  File "test.py", line 17, in <module>
    fmricorr.run()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 490, in _run_interface
    pyfunc=True)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1335, in get_max_resources_used
    num_threads = max(num_threads, _get_num_threads(psutil.Process(pid)))
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1230, in _get_num_threads
    for child in proc.children(recursive=True):
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/__init__.py", line 326, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/__init__.py", line 861, in children
    table[p.ppid()].append(p)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/__init__.py", line 545, in ppid
    return self._proc.ppid()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/_pslinux.py", line 962, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/_pslinux.py", line 1459, in ppid
    return int(self._parse_stat_file()[2])
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/_pslinux.py", line 994, in _parse_stat_file
    data = f.read()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/brain/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/brain/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by djarecka** [comment]
I'm not sure if this is bug in Nipype or something wrong in other libraries. I've seen you created a new issue, so I'll close this one and move discussion there.
