### ISSUE TITLE
Problem with Functions in Nodes when returning matrices

### ISSUE THREAD

**Issue by acamargofb** [nipy/nipype#2156]
I am trying to create a node that calls a function which returns a matrix of 116x116,  the code only works when the function returns matrices of size less than 116x70

This is the code:

```python
from nipype import Node, Function

def fmri_correlation2(dummy):
    import numpy as np
    p_loop = np.random.rand(116, 116)
    print('Dummy func!')
    print(p_loop.shape, type(p_loop))
    return p_loop

fmricorr = Node(Function(input_names=["dummy"],
                         output_names=["P_node"],
                         function=fmri_correlation2),
                name='fmri_correlation2_node')

fmricorr.inputs.dummy = 'test'

fmricorr.run()
print('Done')
```

## Error ###

And this is the traceback messages:

```
brain@neurodebian:~/neuro-csg-pipelines/Projects/Nipype/correlation/Python_CrossCorrelation/version2$ python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    fmricorr = Node(Function(input_names=["dummy"],
NameError: name 'Node' is not defined
brain@neurodebian:~/neuro-csg-pipelines/Projects/Nipype/correlation/Python_CrossCorrelation/version2$ python test.py
170817-14:59:01,239 workflow INFO:
     Executing node fmri_correlation2_node in dir: /tmp/tmpGm6jjh/fmri_correlation2_node
Dummy func!
((116, 116), <type 'numpy.ndarray'>)
^CTraceback (most recent call last):
  File "test.py", line 17, in <module>
    fmricorr.run()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 490, in _run_interface
    pyfunc=True)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1335, in get_max_resources_used
    num_threads = max(num_threads, _get_num_threads(psutil.Process(pid)))
  File "/home/brain/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1230, in _get_num_threads
    for child in proc.children(recursive=True):
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/__init__.py", line 326, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/__init__.py", line 861, in children
    table[p.ppid()].append(p)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/__init__.py", line 545, in ppid
    return self._proc.ppid()
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/_pslinux.py", line 962, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/_pslinux.py", line 1459, in ppid
    return int(self._parse_stat_file()[2])
  File "/home/brain/anaconda2/lib/python2.7/site-packages/psutil/_pslinux.py", line 994, in _parse_stat_file
    data = f.read()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/brain/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/brain/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/home/brain/anaconda2/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Comment by djarecka** [comment]
I can't see this problem and I tried both Python 3.5 and 2.7. In order to test it I would need information about your system and software you're using (you can send the output of the command suggested in issue template ``python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"``).

Does the function run outside the nipype and `Node`?

**Comment by acamargofb** [comment]
Thank you for the fast reply!

Here is the output of the issue template command:

```
{'nibabel_version': '2.0.2', 'networkx_version': '1.11', 'numpy_version': '1.11.1', 'sys_platform': 'linux2', 'sys_version': '2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'commit_source': 'installation', 'commit_hash': '6d8efd7', 'pkg_path': '/home/brain/anaconda2/lib/python2.7/site-packages/nipype', 'sys_executable': '/home/brain/anaconda2/bin/python', 'traits_version': '4.5.0', 'scipy_version': '0.17.1'}
0.12.0
```

About the function, yes it runs both outside and inside nipype, it is a simple random number matrix generated with numpy. The problem comes after: the prints are printed so the function seems to return alright, but then nipype continues to be working without any reason.

It seems to happen only when using numpy, the simple addition code you gave me works alright, even when importing numpy:

```python
def add_2_arg(x_inp_1, x_inp_2):
    import numpy as np
    return np.float(x_inp_1 + x_inp_2)

add = Node(Function(input_names=["x_inp_1", "x_inp_2"],
                       output_names=["val_output"],
                       function=add_2_arg),
              name='add_node')

add.inputs.x_inp_1 =4
add.inputs.x_inp_2 =3
add.run()
print(add.result.outputs)
```

But not if I return a numpy matrix of size above (116,71), up to (116,70) it works fine on my computer but not above.

**Comment by acamargofb** [comment]
I figure it out the problem, the problem was hardware issue. There was not enough CPU and memory available. I did run in other computer and the code works !!! :)

Best,

Aldo

**Comment by djarecka** [comment]
That's great! I'm happy that it works! I will close the issue now. 

btw. you might want to update nipype version, it's 13.1 now.
