### ISSUE TITLE
Testing the install:  "UNEXPECTED EXCEPTION: ImportError("No module named 'bids'",)"

### ISSUE THREAD

**Issue by athanell** [nipy/nipype#2246]
### Summary
While testing the installation with `python -c "import nipype; nipype.test()" ` I got the following error
```
==================================================================================================================================== FAILURES =====================================================================================================================================
_____________________________________________________________________________________________________________________ [doctest] nipype.interfaces.bids_utils ______________________________________________________________________________________________________________________
UNEXPECTED EXCEPTION: ImportError("No module named 'bids'",)
Traceback (most recent call last):

  File "/home/athanell/anaconda3/envs/SAH/lib/python3.5/doctest.py", line 1321, in __run
    compileflags, 1), test.globs)

  File "<doctest nipype.interfaces.bids_utils[1]>", line 1, in <module>

ImportError: No module named 'bids'

/home/athanell/.local/lib/python3.5/site-packages/nipype/interfaces/bids_utils.py:11: UnexpectedException
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================================ 1 failed, 143 passed, 5 skipped in 29.53 seconds =================================================================================================================
```
Is this something that will hinder the usage of nipype and should be fixed? If yes how should I go about it?

Thank you
 

### Platform details:

```
{'nibabel_version': '2.1.0', 'sys_executable': '/home/athanell/anaconda3/envs/SAH/bin/python', 'scipy_version': '0.19.1', 'networkx_version': '2.0', 'sys_platform': 'linux', 'pkg_path': '/home/athanell/.local/lib/python3.5/site-packages/nipype', 'commit_source': 'installation', 'nipype_version': '1.0.0-dev', 'numpy_version': '1.13.3', 'sys_version': '3.5.4 |Anaconda, Inc.| (default, Oct  5 2017, 08:00:22) \n[GCC 7.2.0]', 'commit_hash': 'e4e95f3', 'traits_version': '4.6.0'}
1.0.0-dev

```

**Comment by satra** [comment]
@athanell - good catch there.  yes, this should be fixed.

the doctest should not assume bids is installed. so proper bids check should be in the `tests` folder. these tests should be run when `have_bids` is True. the doctest should be changed so that it doesn't actually run that line using the doctest skip option.

this also means that during the travis test, bids is being installed as a dependency by default, which should not be the case. 

so three things to fix:

1. copy doctests over to the tests folder into a new test file
2. modify doctests to skip the run command
3. fix travis/nipype install so that non-mandatory dependencies are not installed.

if you send a PR, we can help you work through it.

**Comment by athanell** [comment]
Thank you @satra

**Comment by oesteban** [comment]
I pointed this problem out here: https://github.com/nipy/nipype/issues/2207#issuecomment-334313563
