### ISSUE TITLE
IOError: No command "dcm2nii

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/nipype#2360]
### Summary
Hello, I am attempting to utilize a python package named hcpre in order to run some data through the human connectome project minimal preprocessing pipeline. As part of this dicoms are converted into nifti. In order to perform this conversion hcpre piggybacks off of nipype's dcm2nii interface/class, however, when I attempt this it fails on my local machine. This is the error message I receive:

Traceback: 
Traceback (most recent call last):
  File "/home/lnpi14-raid1/timothy-data-lnpi14/nipype_python_2.7.10/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/lnpi14-raid1/timothy-data-lnpi14/nipype_python_2.7.10/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/home/lnpi14-raid1/timothy-data-lnpi14/nipype_python_2.7.10/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/home/lnpi14-raid1/timothy-data-lnpi14/nipype_python_2.7.10/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/home/lnpi14-raid1/timothy-data-lnpi14/nipype_python_2.7.10/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 485, in run
    runtime = self._run_interface(runtime)
  File "/home/lnpi14-raid1/timothy-data-lnpi14/nipype_python_2.7.10/lib/python2.7/site-packages/nipype/interfaces/dcm2nii.py", line 115, in _run_interface
    new_runtime = super(Dcm2nii, self)._run_interface(runtime)
  File "/home/lnpi14-raid1/timothy-data-lnpi14/nipype_python_2.7.10/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 965, in _run_interface
    executable_name, runtime.hostname))
IOError: No command "dcm2nii" found on host lnpi14.cmrr.umn.edu. Please check that the corresponding package is installed.
 
It is almost as if I have to download a dcm2nii binary within a host, but that can't be right... What am I missing?

-Tim

**Comment by effigies** [comment]
Wrapped programs must be installed on the machine running nipype; they're not bundled with nipype.

**Comment by tjhendrickson** [comment]
So to be clear, in this case dcm2nii would have to installed on this machine?

**Comment by effigies** [comment]
Yes.

**Comment by tjhendrickson** [comment]
Perfect! Thanks Chris

Timothy Hendrickson
Department of Psychiatry
University of Minnesota
Bioinformatics and Computational Biology M.S. Candidate
Office: 612-624-6441
Mobile: 507-259-3434 (texts okay)
