### ISSUE TITLE
issue with MIPAV module

### ISSUE THREAD

**Issue by fBeyer89** [nipy/nipype#2362]
Dear all,
I've tried to run the example on MP2RAGE-skullstripping  http://nipype.readthedocs.io/en/latest/users/examples/smri_cbs_skullstripping.html with nipype 0.14.0 and CBStools version 3.0. I use a conda environment based on python 2.7.

Here is the error message:
Traceback: 
Traceback (most recent call last):
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1063, in run
    env['DISPLAY'] = config.get_display()
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/utils/config.py", line 286, in get_display
    ndisp = int(sysdisplay.split(':')[-1])
ValueError: invalid literal for int() with base 10: '0.0'

When running the MIPAV command separately it works fine. 

Do you have an idea what could be the reason for this?
Best
Frauke

**Comment by mgxd** [comment]
@fBeyer89 thanks for reporting this, what OS are you running?

**Comment by fBeyer89** [comment]
I am running on a 16.04.1. Ubuntu machine (Linux lessing 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
