### ISSUE TITLE
docs not building

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2466]
on readthedocs:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nipype/envs/latest/lib/python3.5/site-packages/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ImportError: No module named 'numpydoc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nipype/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nipype/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nipype/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nipype/envs/latest/lib/python3.5/site-packages/sphinx/registry.py", line 199, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension numpydoc (exception: No module named 'numpydoc')

Extension error:
Could not import extension numpydoc (exception: No module named 'numpydoc')
```

**Comment by effigies** [comment]
Adding numpydoc to `rtd_requirements.txt` will probably resolve it, but I don't know how to test that off of master.

**Comment by satra** [comment]
just made a direct change - which triggered a new build - will see if this passes.

**Comment by satra** [comment]
works now.
