### ISSUE TITLE
ImportError: cannot import name '__version__'

### ISSUE THREAD

**Issue by ggsf13** [nipy/nipype#2507]
### Summary
After I install nipype, I tried  "import nipype; print(nipype.__version__)" , but I got an error ImportError: cannot import name '__version__'
### Actual behavior
here is the detail:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\__init__.py", line 51, in <module>
    from .pipeline import Node, MapNode, JoinNode, Workflow
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\pipeline\__init__.py", line 11, in <module>
    from .engine import Node, MapNode, JoinNode, Workflow
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\pipeline\engine\__init__.py", line 12, in <module>
    from .workflows import Workflow
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\pipeline\engine\workflows.py", line 36, in <module>
    from ...interfaces.base import (traits, TraitedSpec, TraitDictObject,
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\interfaces\__init__.py", line 13, in <module>
    from .io import DataGrabber, DataSink, SelectFiles, BIDSDataGrabber
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\interfaces\io.py", line 43, in <module>
    from .base import (
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\interfaces\base\__init__.py", line 11, in <module>
    from .core import (Interface, BaseInterface, SimpleInterface, CommandLine,
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\interfaces\base\core.py", line 44, in <module>
    from .traits_extension import traits, isdefined, TraitError
  File "D:\softwares\Annoconda3\lib\site-packages\nipype\interfaces\base\traits_extension.py", line 31, in <module>
    from traits import __version__ as traits_version
ImportError: cannot import name '__version__'
```
### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by mgxd** [comment]
@ggsf13 can you try 
```
"import nipype; print(nipype.__version__)"

**Comment by ggsf13** [comment]
@mgxd I've tried this, but there is still the same problem: ImportError: cannot import name '__version__' .

**Comment by effigies** [comment]
Do you have traits installed? How did you install nipype?

**Comment by ggsf13** [comment]
@effigies I have traits installed and I install nipype by pip install nipype.

**Comment by ggsf13** [comment]
I solved the problem by reinstall traits again
