### ISSUE TITLE
Error while checking node hash and pickle protocol

### ISSUE THREAD

**Issue by djarecka** [nipy/nipype#2540]
Has anyone had this kind of error?  Python actually didn't exit after this errors, but it's not doing anything...

I installed `nipype` with `conda` on `py27`

```
	 [Job 0] Cached (metaflow.AnnArbor_sub16960.download_url).
180412-17:36:07,419 workflow WARNING:
	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:

	Node: metaflow.AnnArbor_sub16960.reorient_brain
	Interface: nipype.interfaces.fsl.utils.Reorient2Std
	Traceback:
Traceback (most recent call last):

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 341, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 302, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 496, in _get_hashval
    self._get_inputs()

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 523, in _get_inputs
    results = loadpkl(results_file)

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 641, in loadpkl
    unpkl = pickle.load(pkl_file)

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)

  File "/Users/dorota/anaconda/envs/simple_py2/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto

ValueError: unsupported pickle protocol: 3
```

**Comment by oesteban** [comment]
Was the node really cached?

**Comment by djarecka** [comment]
so I believe this might be related that I was changing conda environments. I believe that I already changed at least one from py to py3 and it was fine, but when I came back to py2, I had this problem. Is this just can happen when I change the environments?

**Comment by djarecka** [comment]
oh, I should also add that ever time my workflow was failing, so it didn't finish the job (however I saw some outputs)

**Comment by oesteban** [comment]
> but when I came back to py2, I had this problem. Is this just can happen when I change the environments?

Yes, reading py3 pickles from py2 will generally raise this `ValueError`. So, if the node was cached, this is the most likely explanation to this error.

> oh, I should also add that ever time my workflow was failing, so it didn't finish the job (however I saw some outputs)

I don't understand what you mean here, can you explain a bit further?
