### ISSUE TITLE
ValueError when running NiftyReg node

### ISSUE THREAD

**Issue by fepegar** [nipy/nipype#2616]
### Summary
I get this error when running a NiftyReg registration or resampling: `ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr`.

### Actual behavior
```python-traceback
C:\Users\fernando\tmp
(vesseg) λ python r.py
180612-16:47:31,795 interface WARNING:
         version_from_command member of CommandLine was Deprecated in nipype-1.0.0 and deleted in 1.1.0
180612-16:47:31,866 interface WARNING:
         version_from_command member of CommandLine was Deprecated in nipype-1.0.0 and deleted in 1.1.0
Traceback (most recent call last):
  File "r.py", line 11, in <module>
    aladin.run()
  File "C:\Users\fernando\Miniconda3\envs\vesseg\lib\site-packages\nipype\interfaces\base\core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "C:\Users\fernando\Miniconda3\envs\vesseg\lib\site-packages\nipype\interfaces\base\core.py", line 1041, in _run_interface
    runtime = run_command(runtime, output=self.terminal_output)
  File "C:\Users\fernando\Miniconda3\envs\vesseg\lib\site-packages\nipype\interfaces\base\core.py", line 778, in run_command
    close_fds=True,
  File "C:\Users\fernando\Miniconda3\envs\vesseg\lib\subprocess.py", line 624, in __init__
    "close_fds is not supported on Windows platforms"
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

### How to replicate the behavior
Run:
```python
import pathlib
from nipype.interfaces import niftyreg

data_dir = pathlib.Path('~/tmp/oeslle').expanduser()
ref_path = flo_path = str(data_dir / 't1.nii.gz')

aladin = niftyreg.RegAladin()
aladin.inputs.ref_file = ref_path
aladin.inputs.flo_file = flo_path
aladin.inputs.lp_val = 1
aladin.run()
```

This 
```python
subprocess.call(aladin.cmdline.split())
```
works on that little script, but in a larger script Windows shows an error and the script stops working. I haven't been able to reproduce that, though.

### Platform details:
```python
In [1]: import nipype

In [2]: nipype.get_info()
Out[2]:
{'pkg_path': 'C:\\Users\\fernando\\Miniconda3\\envs\\vesseg\\lib\\site-packages\\nipype',
 'commit_source': 'archive substitution',
 'commit_hash': '%h',
 'nipype_version': '1.0.4',
 'sys_version': '3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]',
 'sys_executable': 'C:\\Users\\fernando\\Miniconda3\\envs\\vesseg\\python.exe',
 'sys_platform': 'win32',
 'numpy_version': '1.14.3',
 'scipy_version': '1.1.0',
 'networkx_version': '2.1',
 'nibabel_version': '2.2.1',
 'traits_version': '4.6.0'}

In [3]: nipype.__version__
Out[3]: '1.0.4'
```

### Execution environment
I'm not sure what this means. I'm running Python from a `conda` environment.

**Comment by oesteban** [comment]
Pinging @byvernault here. I would guess that means you'll need to set a different `terminal_output` when running on Windows.

**Comment by fepegar** [comment]
I'm not sure what you mean. I haven't set that variable.

**Comment by mgxd** [comment]
@fepegar could you try out the example below?

```python
from nipype.interfaces.base import CommandLine
CommandLine("ls").run()
```

**Comment by fepegar** [comment]
@mgxd I get the same error

**Comment by fepegar** [comment]
@mgxd I tried to hack the code using your commit, 1776ed43c565258215b695da11d54d9e3b8c4c2c, and got:
```
~\Miniconda3\envs\vesseg\lib\site-packages\nipype\interfaces\base\core.py in run_command(runtime, output, timeout)
    776         cwd=runtime.cwd,
    777         env=env,
--> 778         close_fds=(not sys.platform.startswith('win')),
    779     )
    780

~\Miniconda3\envs\vesseg\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

~\Miniconda3\envs\vesseg\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

TypeError: environment can only contain strings
```

**Comment by mgxd** [comment]
@fepegar I pushed a possible fix on my pr, but haven't tested it - could you try testing it? Looks like our windows support is still in alpha :smiley:

**Comment by fepegar** [comment]
Alright. How do you suggest I test that? Making the same changes to my nipype code and running again? Creating a new environment and pip-installing your fork?

**Comment by mgxd** [comment]
@fepegar you can directly install my fork with

`pip install -U https://github.com/mgxd/nipype/archive/fix/win.zip`

**Comment by fepegar** [comment]
I had actually installed `nipype` using `conda` instead of `pip`. When I install it with `pip` (master or your fork) I get an error:
```python-traceback
C:\Users\fernando\git\vesseg\vesseg (master)
(nipype) λ ipython
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from nipype.interfaces.base import CommandLine
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-e8e7b3e1d745> in <module>()
----> 1 from nipype.interfaces.base import CommandLine

~\Miniconda3\envs\nipype\lib\site-packages\nipype\__init__.py in <module>()
     10 from .info import (LONG_DESCRIPTION as __doc__, URL as __url__, STATUS as
     11                    __status__, __version__)
---> 12 from .utils.config import NipypeConfig
     13 from .utils.logger import Logging
     14 from .refs import due

~\Miniconda3\envs\nipype\lib\site-packages\nipype\utils\__init__.py in <module>()
      2 from __future__ import absolute_import
      3
----> 4 from .config import NUMPY_MMAP
      5 from .onetime import OneTimeProperty, setattr_on_read
      6 from .tmpdirs import TemporaryDirectory, InTemporaryDirectory

~\Miniconda3\envs\nipype\lib\site-packages\nipype\utils\config.py in <module>()
     26
     27 from .misc import str2bool
---> 28 from ..external import portalocker
     29
     30 standard_library.install_aliases()

~\Miniconda3\envs\nipype\lib\site-packages\nipype\external\portalocker.py in <module>()
     72
     73 if os.name == 'nt':
---> 74     import win32con
     75     import win32file
     76     import pywintypes

ModuleNotFoundError: No module named 'win32con'
```

**Comment by mgxd** [comment]
could you try `pip install pypiwin32` before installing nipype?

**Comment by fepegar** [comment]
After installing `pypiwin32` I get [this error](https://github.com/nipy/nipype/issues/2616#issuecomment-396661313)
I tried converting the items  of `env` to `str` like [here](https://github.com/c4urself/bump2version/pull/12/commits/388af758bc01d3fa7cecb0f02eb5568a2d84db85), but got this:
```python-traceback
OSError                                   Traceback (most recent call last)
~\Miniconda3\envs\nipype\lib\site-packages\nipype\interfaces\base\core.py in _process(drain)
    801             try:
--> 802                 res = select.select(streams, [], [], timeout)
    803             except select.error as e:

OSError: [WinError 10038] An operation was attempted on something that is not a socket

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-73c0347eafb3> in <module>()
----> 1 CommandLine("ls").run()

~\Miniconda3\envs\nipype\lib\site-packages\nipype\interfaces\base\core.py in run(self, cwd, ignore_exception, **inputs)
    519         try:
    520             runtime = self._pre_run_hook(runtime)
--> 521             runtime = self._run_interface(runtime)
    522             runtime = self._post_run_hook(runtime)
    523             outputs = self.aggregate_outputs(runtime)

~\Miniconda3\envs\nipype\lib\site-packages\nipype\interfaces\base\core.py in _run_interface(self, runtime, correct_return_codes)
   1046                                                  runtime.environ)
   1047                                 if self._ldd else '<skipped>')
-> 1048         runtime = run_command(runtime, output=self.terminal_output)
   1049         if runtime.returncode is None or \
   1050                 runtime.returncode not in correct_return_codes:

~\Miniconda3\envs\nipype\lib\site-packages\nipype\interfaces\base\core.py in run_command(runtime, output, timeout)
    813         while proc.returncode is None:
    814             proc.poll()
--> 815             _process()
    816
    817         _process(drain=1)

~\Miniconda3\envs\nipype\lib\site-packages\nipype\interfaces\base\core.py in _process(drain)
    803             except select.error as e:
    804                 iflogger.info(e)
--> 805                 if e[0] == errno.EINTR:
    806                     return
    807                 else:

TypeError: 'OSError' object is not subscriptable
```
