### ISSUE TITLE
FreeSurfer Reconall Error

### ISSUE THREAD

**Issue by PkuClosed** [nipy/nipype#2632]
### Summary

An error was encountered when running the freesurfer pipeline. The pipeline complains: could not run node: ReconAll.config.

I have not found a counterpart for ReconAll.config in the original FreeSurfer, and the error message does not seem to give much information. I am wondering how I can fix this problem

### Actual behavior

Because the log is very long, I have posted the part that I feel relevant below.
`
[Node] Finished "ReconAll.AutoRecon1.Normalize_T1".
180703-13:35:17,779 workflow INFO:
         [Node] Setting-up "ReconAll.AutoRecon1.T2_Convert" in "/data/chuyangye/harmonization/CDMRI_data/freesurfer/connectom/sub_0000/ReconAll/AutoRecon1/T2_Convert".
180703-13:35:17,785 workflow INFO:
         [Node] Running "T2_Convert" ("nipype.interfaces.utility.wrappers.Function")
180703-13:35:17,799 workflow INFO:
         [Node] Finished "ReconAll.AutoRecon1.T2_Convert".
180703-13:35:17,801 workflow INFO:
         ***********************************
180703-13:35:17,802 workflow ERROR:
         could not run node: ReconAll.config
180703-13:35:17,803 workflow INFO:
         crashfile: /home/chuyangye/crash-20180703-133032-chuyangye-config-12761c34-aa0c-432f-bb27-79de9d9c3e3d.pklz
180703-13:35:17,804 workflow INFO:
         ***********************************
`

I have also looked at the crash file, which gives the following information:

```
File: /home/chuyangye/crash-20180703-133032-chuyangye-config-12761c34-aa0c-432f-bb27-79de9d9c3e3d.pklz
Node: ReconAll.config
Working directory: /data/chuyangye/harmonization/CDMRI_data/freesurfer/connectom/sub_0000/ReconAll/config


Node inputs:

awk_file = <undefined>
color_table = <undefined>
function_str = def setconfig(reg_template=None,
              reg_template_withskull=None,
              lh_atlas=None,
              rh_atlas=None,
              lh_classifier1=None,
              rh_classifier1=None,
              lh_classifier2=None,
              rh_classifier2=None,
              lh_classifier3=None,
              rh_classifier3=None,
              src_subject_id=None,
              src_subject_dir=None,
              color_table=None,
              lookup_table=None,
              wm_lookup_table=None,
              awk_file=None,
              rb_date=None):
    """Set optional configurations to the default"""

    def checkarg(arg, default):
        """Returns the value if defined; otherwise default"""
        if arg:
            return arg
        else:
            return default

    defaultconfig = getdefaultconfig(exitonfail=True, rb_date=rb_date)
    # set the default template and classifier files
    reg_template = checkarg(reg_template,
                            defaultconfig['registration_template'])
    reg_template_withskull = checkarg(
        reg_template_withskull,
        defaultconfig['registration_template_withskull'])
    lh_atlas = checkarg(lh_atlas, defaultconfig['lh_atlas'])
    rh_atlas = checkarg(rh_atlas, defaultconfig['rh_atlas'])
    lh_classifier1 = checkarg(lh_classifier1,
                              defaultconfig['lh_classifier'])
    rh_classifier1 = checkarg(rh_classifier1,
                              defaultconfig['rh_classifier'])
    lh_classifier2 = checkarg(lh_classifier2,
                              defaultconfig['lh_classifier2'])
    rh_classifier2 = checkarg(rh_classifier2,
                              defaultconfig['rh_classifier2'])
    lh_classifier3 = checkarg(lh_classifier3,
                              defaultconfig['lh_classifier3'])
    rh_classifier3 = checkarg(rh_classifier3,
                              defaultconfig['rh_classifier3'])
    src_subject_id = checkarg(src_subject_id,
                              defaultconfig['src_subject_id'])
    src_subject_dir = checkarg(src_subject_dir,
                               defaultconfig['src_subject_dir'])
    color_table = checkarg(color_table, defaultconfig['AvgColorTable'])
    lookup_table = checkarg(lookup_table, defaultconfig['LookUpTable'])
    wm_lookup_table = checkarg(wm_lookup_table,
                               defaultconfig['WMLookUpTable'])
    awk_file = checkarg(awk_file, defaultconfig['awk_file'])
    return reg_template, reg_template_withskull, lh_atlas, rh_atlas, \
        lh_classifier1, rh_classifier1, lh_classifier2, rh_classifier2, \
        lh_classifier3, rh_classifier3, src_subject_id, src_subject_dir, \
        color_table, lookup_table, wm_lookup_table, awk_file

ignore_exception = False
lh_atlas = <undefined>
lh_classifier1 = <undefined>
lh_classifier2 = <undefined>
lh_classifier3 = <undefined>
lookup_table = <undefined>
rb_date = 2014-08-21
reg_template = <undefined>
reg_template_withskull = <undefined>
rh_atlas = <undefined>
rh_classifier1 = <undefined>
rh_classifier2 = <undefined>
rh_classifier3 = <undefined>
src_subject_dir = <undefined>
src_subject_id = <undefined>
wm_lookup_table = <undefined>



Traceback:
Traceback (most recent call last):
  File "/home/chuyangye/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/chuyangye/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/home/chuyangye/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/home/chuyangye/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/chuyangye/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/home/chuyangye/anaconda2/lib/python2.7/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 27, in setconfig
NameError: global name 'getdefaultconfig' is not defined
```

### Script/Workflow details

The code for running the pipeline is

```
recon_all = create_reconall_workflow()
recon_all.base_dir = out_dir
recon_all.inputs.inputspec.subject_id = out_dir
recon_all.inputs.inputspec.subjects_dir = directory
recon_all.inputs.inputspec.T1_files = T1name
recon_all.run()  
```

### Platform details:

{'nibabel_version': '2.3.0', 'sys_executable': '/home/chuyangye/anaconda2/bin/python', 'networkx_version': '2.1', 'numpy_version': '1.14.5', 'sys_platform': 'linux2', 'sys_version': '2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) \n[GCC 7.2.0]', 'commit_source': 'installation', 'commit_hash': 'fed0bd94f', 'pkg_path': '/home/chuyangye/anaconda2/lib/python2.7/site-packages/nipype', 'nipype_version': '1.0.4', 'traits_version': '4.6.0', 'scipy_version': '1.1.0'}
1.0.4

**Comment by effigies** [comment]
I would not recommend using the `recon-all` workflow. It was developed at a point between 5.3 and 6.0, and does not correspond to a released version of FreeSurfer.

That said, the issue is that this function does not import `getdefaultconfig` within the local scope:

https://github.com/nipy/nipype/blob/f79581edc042ed38064f48e85b6dcc38bc30a084/nipype/workflows/smri/freesurfer/recon.py#L190-L249

It should include it as follows:

```Python
from nipype.workflows.smri.freesurfer.utils import getdefaultconfig
```

**Comment by PkuClosed** [comment]
@effigies Thanks for the reply. I am wondering what would be the recommended way of running freesufer.

**Comment by effigies** [comment]
Oh, sorry for not responding. The recommended way is the [ReconAll](https://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.freesurfer/preprocess.html#reconall) interface.

**Comment by mgxd** [comment]
@PkuClosed feel free to reopen this if you have further questions

**Comment by jdalrymple** [comment]
Just ran the ReconAll interface and got the same result as with the reconall workflow:

```
   recon_all = ReconAll()
    recon_all.inputs.inputspec.subject_id = id
    recon_all.inputs.inputspec.subjects_dir = data_dst_dir
    recon_all.inputs.inputspec.T1_files = src_path
    recon_all.run() 
```

Results:

```
...
    return self._run_command(execute)
  File "/src/nipype/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/src/nipype/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/src/nipype/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 27, in setconfig
NameError: name 'getdefaultconfig' is not defined
...
```

Any suggestions?

**Comment by effigies** [comment]
It's not clear how you would get this result from trying to use the `ReconAll` interface, as it does not involve a `Function` interface. Can you post your exact code?

**Comment by effigies** [comment]
And can you start a new issue, when you do?
