### ISSUE TITLE
nipypecli ImportError

### ISSUE THREAD

**Issue by jacquelineharris** [nipy/nipype#2646]
### Summary

Hi, 

I'm trying to use nipypecli in terminal to view my crash files but I keep getting the error 

ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

Any idea how to fix this?

### Platform details:

{'pkg_path': '/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype', 'commit_source': 'archive substitution', 'commit_hash': '%h', 'nipype_version': '1.1.0', 'sys_version': '3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]', 'sys_executable': '/Users/jacqueline.harris/anaconda3/bin/python', 'sys_platform': 'darwin', 'numpy_version': '1.13.3', 'scipy_version': '0.19.1', 'networkx_version': '2.1', 'nibabel_version': '2.3.0', 'traits_version': '4.6.0'}
1.1.0

### Execution environment
- My python environment outside container

**Comment by mgxd** [comment]
@jacquelineharris it sounds like you have mismatching versions of python installed in the same environment.

You could check your `$PATH` and `$PYTHONPATH` environmental variables for any traces of older (probably py27) versions and remove them, or make a fresh environment and retry.

**Comment by jacquelineharris** [comment]
The full error message is below. I tried checking the $PATH and $PYTHONPATH variables but neither have any mention of python 2.x

/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/utils/logger.py:20: UserWarning: ConcurrentLogHandler not installed. Using builtin log handler
  warn("ConcurrentLogHandler not installed. Using builtin log handler")
Traceback (most recent call last):
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/utils/logger.py", line 16, in <module>
    from ..external.cloghandler import ConcurrentRotatingFileHandler as \
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/external/cloghandler.py", line 59, in <module>
    from logging.handlers import BaseRotatingHandler
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/logging/handlers.py", line 28, in <module>
    import queue
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/queue/__init__.py", line 8, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacqueline.harris/anaconda3/bin/nipypecli", line 11, in <module>
    load_entry_point('nipype==1.1.0', 'console_scripts', 'nipypecli')()
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/__init__.py", line 13, in <module>
    from .utils.logger import Logging
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/utils/logger.py", line 21, in <module>
    from logging.handlers import RotatingFileHandler as RFHandler
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/logging/handlers.py", line 28, in <module>
    import queue
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/queue/__init__.py", line 8, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/utils/logger.py:20: UserWarning: ConcurrentLogHandler not installed. Using builtin log handler
  warn("ConcurrentLogHandler not installed. Using builtin log handler")
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/utils/logger.py", line 16, in <module>
    from ..external.cloghandler import ConcurrentRotatingFileHandler as \
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/external/cloghandler.py", line 59, in <module>
    from logging.handlers import BaseRotatingHandler
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/logging/handlers.py", line 28, in <module>
    import queue
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/queue/__init__.py", line 8, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/__init__.py", line 13, in <module>
    from .utils.logger import Logging
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/nipype/utils/logger.py", line 21, in <module>
    from logging.handlers import RotatingFileHandler as RFHandler
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/logging/handlers.py", line 28, in <module>
    import queue
  File "/Users/jacqueline.harris/anaconda3/lib/python3.6/site-packages/queue/__init__.py", line 8, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

**Comment by djarecka** [comment]
@jacquelineharris - have you just created the `crashflie` or is it possible that you're trying to read an old file? I think once I had a similar error when I tried to read a crashflie generated in different env.

**Comment by jacquelineharris** [comment]
No, unfortunately these are new crash files from the same env

**Comment by mgxd** [comment]
@jacquelineharris there's a couple things you can try

1. `pip install --force-reinstall -U future`

if that doesn't work...

2. create a fresh environment and retry the installation

**Comment by jacquelineharris** [comment]
Thanks @mgdx, that did it!

**Comment by mgxd** [comment]
great!
