### ISSUE TITLE
"nipypecli crash" does not enter debugger.

### ISSUE THREAD

**Issue by effigies** [nipy/nipype#2684]
### Summary

Wanted to try out entering the debugger from a crash file. `-d` and `-i` seem to have no effect.

### Actual behavior

```
$ nipypecli crash -d crash-20180816-195957-neuro-l2_model-fa815635-6797-4bf2-8380-c80730d27c3d.pklz


File: /work/crash-20180816-195957-neuro-l2_model-fa815635-6797-4bf2-8380-c80730d27c3d.pklz
Node: fitlins_wf.l2_model
Working directory: /work/scratch/zPY/fitlins_wf/l2_model


Node inputs:

contrast_indices = [[{'contrast': 'brightness', 'run': 1, 'subject': 'rid000006', 'task': 'life'}, {'contrast': 'brightness', 'run': 1, 'subject': 'rid000009', 'task': 'life'}]]
contrast_info = ['/work/scratch/zPY/fitlins_wf/loader/dataset/run-1_task-life_contrasts.h5']
stat_files = <undefined>
stat_metadata = <undefined>



Traceback:
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1250, in _run_interface
    self.config['execution']['stop_on_first_crash'])))
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1172, in _collate_results
    (self.name, '\n'.join(msg)))
Exception: Subnodes of node: l2_model failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 106, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)

  File "/src/fitlins/fitlins/interfaces/nistats.py", line 202, in _run_interface
    raise ValueError('IDX: {!r}; METADATA: {!r}'.format(idx, metadata))

ValueError: IDX: {'contrast': 'brightness', 'run': 1, 'subject': 'rid000006', 'task': 'life'}; METADATA: {'acq': '374vol', 'acquisition': '374vol', 'contrast': 'FramewiseDisplacement', 'modality': 'func', 'run': '1', 'space': 'MNI152NLin2009cAsym', 'subject': 'rid000009', 'task': 'life', 'type': 'effect'}
```

### Expected behavior

I would enter the debugger.

### How to replicate the behavior

I suspect trying to debug any crashfile.

### Script/Workflow details

https://github.com/poldracklab/fitlins/

### Platform details:

```
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.1',
 'nibabel_version': '2.3.0',
 'nipype_version': '1.1.2',
 'numpy_version': '1.14.1',
 'pkg_path': '/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.0.0',
 'sys_executable': '/opt/conda/envs/neuro/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) \n'
                '[GCC 7.2.0]',
 'traits_version': '4.6.0'}
```

### Execution environment

Choose one
- Container - augmented version of poldracklab/fitlins:0.0.6 to include neuroscout-cli and jupyterlab, with live repos of neuroscout and fitlins mounted

**Comment by satra** [comment]
i believe it requires `-d` and  `-r` (rerun/reexecute)

```
$ nipypecli crash -h
Usage: nipypecli crash [OPTIONS] CRASHFILE

  Display Nipype crash files.

  For certain crash files, one can rerun a failed node in a temp directory.

  Examples:

  nipypecli crash crashfile.pklz

  nipypecli crash crashfile.pklz -r -i

Options:
  -r, --rerun          Rerun crashed node.
  -d, --debug          Enable Python debugger when re-executing.
  -i, --ipydebug       Enable IPython debugger when re-executing.
  -w, --dir DIRECTORY  Directory where to run the node in.
  -h, --help           Show this message and exit.
```

**Comment by effigies** [comment]
Good catch. Sorry for the noise.
