### ISSUE TITLE
dMRI: Connectivity - Camino, CMTK, FreeSurfer workflow error: The 'outputtracts' trait of a ProcStreamlinesInputSpec instance must be a boolean, but a value of 'oogl' <type 'str'> was specified.

### ISSUE THREAD

**Issue by avatar-lavventura** [nipy/nipype#2742]
I am trying to run `dMRI: Connectivity - Camino, CMTK, FreeSurfer` workflow 
that is provided under nipype's website, please see its [link](https://nipype.readthedocs.io/en/0.12.0/users/examples/dmri_connectivity.html).

```
$ wget -c http://fsl.fmrib.ox.ac.uk/fslcourse/downloads/fdt.tar.gz
$ tar -xzvf fdt.tar.gz  #extracted folders are fdt1 and fdt2
# updated following line data_dir = op.abspath('fsl_course_data/fdt/') with data_dir = op.abspath('fdt2') on the source code
$ python sourceCode.py
Traceback (most recent call last):
  File "sourceCode.py", line 194, in <module>
    procstreamlines.inputs.outputtracts = 'oogl'
  File "/home/netlab/.local/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'outputtracts' trait of a ProcStreamlinesInputSpec instance must be a boolean, but a value of 'oogl' <type 'str'> was specified.
```

**[Q]** How could I fix the error I am having? I have followed the given guide which does not work.

**Comment by mgxd** [comment]
hi @avatar-lavventura - the error is in L194 of `sourceCode.py`. If you want to save output streamlines in raw binary format, change the line to

```
procstreamlines.inputs.outputtracts = True
```

**Comment by avatar-lavventura** [comment]
I have made the required change but now having much more errors. Are you able to run this example? Could it be because of the `fdt` path I am providing?

```
181023-17:53:23,648 nipype.workflow INFO:
	 Workflow workflow settings: ['check', 'execution', 'logging', 'monitoring']
181023-17:53:23,659 nipype.workflow INFO:
	 Running serially.
181023-17:53:23,659 nipype.workflow INFO:
	 [Node] Setting-up "workflow.datasource" in "/home/netlab/nipype/deneme/camino_dti_tutorial/workflow/_subject_id_subj1/datasource".
181023-17:53:23,663 nipype.workflow INFO:
	 [Node] Running "datasource" ("nipype.interfaces.io.DataGrabber")
181023-17:53:23,668 nipype.workflow INFO:
	 [Node] Finished "workflow.datasource".
181023-17:53:23,668 nipype.workflow INFO:
	 [Node] Setting-up "workflow.tractography.image2voxel" in "/home/netlab/nipype/deneme/camino_dti_tutorial/workflow/tractography/_subject_id_subj1/image2voxel".
181023-17:53:23,671 nipype.workflow INFO:
	 [Node] Running "image2voxel" ("nipype.interfaces.camino.convert.Image2Voxel"), a CommandLine Interface with command:
image2voxel -4dimage /home/netlab/nipype/deneme/fdt1/subj1/data.nii.gz -outputdatatype float > data.Bfloat
181023-17:53:23,673 nipype.workflow WARNING:
	 [Node] Error on "workflow.tractography.image2voxel" (/home/netlab/nipype/deneme/camino_dti_tutorial/workflow/tractography/_subject_id_subj1/image2voxel)
181023-17:53:23,675 nipype.workflow ERROR:
	 Node image2voxel.a0 failed to run on host sametaytac-HP-Z240-Tower-Workstation.
181023-17:53:23,675 nipype.workflow ERROR:
	 Saving crash info to /home/netlab/nipype/deneme/crash-20181023-175323-netlab-image2voxel.a0-2d9d416c-dedf-4d62-9d4c-0aded4e5c6c2.pklz
Traceback (most recent call last):
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 1029, in _run_interface
    runtime.hostname))
IOError: No command "image2voxel" found on host sametaytac-HP-Z240-Tower-Workstation. Please check that the corresponding package is installed.

181023-17:53:23,677 nipype.workflow INFO:
	 [Node] Setting-up "workflow.tractography.fsl2scheme" in "/home/netlab/nipype/deneme/camino_dti_tutorial/workflow/tractography/_subject_id_subj1/fsl2scheme".
181023-17:53:23,681 nipype.workflow INFO:
	 [Node] Running "fsl2scheme" ("nipype.interfaces.camino.convert.FSL2Scheme"), a CommandLine Interface with command:
fsl2scheme -bvecfile /home/netlab/nipype/deneme/fdt1/subj1/bvecs -bvalfile /home/netlab/nipype/deneme/fdt1/subj1/bvals -usegradmod > bvecs.scheme
181023-17:53:23,683 nipype.workflow WARNING:
	 [Node] Error on "workflow.tractography.fsl2scheme" (/home/netlab/nipype/deneme/camino_dti_tutorial/workflow/tractography/_subject_id_subj1/fsl2scheme)
181023-17:53:23,686 nipype.workflow ERROR:
	 Node fsl2scheme.a0 failed to run on host sametaytac-HP-Z240-Tower-Workstation.
181023-17:53:23,686 nipype.workflow ERROR:
	 Saving crash info to /home/netlab/nipype/deneme/crash-20181023-175323-netlab-fsl2scheme.a0-035d1312-e6c5-4b82-9922-00a7c1d69f86.pklz
Traceback (most recent call last):
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 1029, in _run_interface
    runtime.hostname))
IOError: No command "fsl2scheme" found on host sametaytac-HP-Z240-Tower-Workstation. Please check that the corresponding package is installed.

181023-17:53:23,688 nipype.workflow INFO:
	 [Node] Setting-up "workflow.tractography.bet" in "/home/netlab/nipype/deneme/camino_dti_tutorial/workflow/tractography/_subject_id_subj1/bet".
181023-17:53:23,691 nipype.workflow INFO:
	 [Node] Running "bet" ("nipype.interfaces.fsl.preprocess.BET"), a CommandLine Interface with command:
bet /home/netlab/nipype/deneme/fdt1/subj1/data.nii.gz /home/netlab/nipype/deneme/camino_dti_tutorial/workflow/tractography/_subject_id_subj1/bet/data_brain.nii -m
181023-17:53:23,693 nipype.workflow WARNING:
	 [Node] Error on "workflow.tractography.bet" (/home/netlab/nipype/deneme/camino_dti_tutorial/workflow/tractography/_subject_id_subj1/bet)
181023-17:53:23,696 nipype.workflow ERROR:
	 Node bet.a0 failed to run on host sametaytac-HP-Z240-Tower-Workstation.
181023-17:53:23,696 nipype.workflow ERROR:
	 Saving crash info to /home/netlab/nipype/deneme/crash-20181023-175323-netlab-bet.a0-41778ddc-67c4-4f87-8afe-47a5f5c871a9.pklz
Traceback (most recent call last):
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/interfaces/fsl/preprocess.py", line 142, in _run_interface
    runtime = super(BET, self)._run_interface(runtime)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 1029, in _run_interface
    runtime.hostname))
IOError: No command "bet" found on host sametaytac-HP-Z240-Tower-Workstation. Please check that the corresponding package is installed.

181023-17:53:23,698 nipype.workflow INFO:
	 ***********************************
181023-17:53:23,698 nipype.workflow ERROR:
	 could not run node: workflow.tractography.image2voxel.a0
181023-17:53:23,698 nipype.workflow INFO:
	 crashfile: /home/netlab/nipype/deneme/crash-20181023-175323-netlab-image2voxel.a0-2d9d416c-dedf-4d62-9d4c-0aded4e5c6c2.pklz
181023-17:53:23,698 nipype.workflow ERROR:
	 could not run node: workflow.tractography.fsl2scheme.a0
181023-17:53:23,698 nipype.workflow INFO:
	 crashfile: /home/netlab/nipype/deneme/crash-20181023-175323-netlab-fsl2scheme.a0-035d1312-e6c5-4b82-9922-00a7c1d69f86.pklz
181023-17:53:23,698 nipype.workflow ERROR:
	 could not run node: workflow.tractography.bet.a0
181023-17:53:23,698 nipype.workflow INFO:
	 crashfile: /home/netlab/nipype/deneme/crash-20181023-175323-netlab-bet.a0-41778ddc-67c4-4f87-8afe-47a5f5c871a9.pklz
181023-17:53:23,698 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "dd.py", line 316, in <module>
    workflow.run()
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 61, in run
    report_nodes_not_run(notrun)
  File "/home/netlab/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```

**Comment by mgxd** [comment]
it looks like camino and and fsl are not in your PATH - are they installed on your computer? If so, you probably just need to `export PATH` and ensure it has the correct install locations.
Here are the install docs for [camino](http://camino.cs.ucl.ac.uk/index.php?n=Main.Installation) and [FSL](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation#Installing_FSL)
