### ISSUE TITLE
Program works in Jupyter Notebook but not with Spyder

### ISSUE THREAD

**Issue by KirkGraff** [nipy/nipype#2795]
Hi all, I'm trying to get into Nipype, but I'm having some issues. My very basic program works in Jupyter Notebook, but not in Spyder. The code looks something like this:

import os
os.chdir("some directory")

import nipype.interfaces.fsl as fsl
input_file = "sub-1089001_ses-0_T1ww.nii.gz"

mybet = fsl.BET()
mybet.inputs.in_file = input_file
mybet.inputs.frac = 0.7
mybet.inputs.out_file = "T1bet.nii.gz"
res = mybet.run()

Running this code in a Jupyter Notebook works perfectly, and it skull strips my T1. Running it in Spyder spits out a bunch of error messages, as follows:

FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
Traceback (most recent call last):

  File "<ipython-input-1-864807b6ebce>", line 1, in <module>
    runfile('some directory/nipype.py', wdir='some directory')

  File "/Users/ivy/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/Users/ivy/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "some directory/nipype.py", line 25, in <module>
    res = mybet.run()

  File "/Users/ivy/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)

  File "/Users/ivy/anaconda3/lib/python3.6/site-packages/nipype/interfaces/fsl/preprocess.py", line 142, in _run_interface
    runtime = super(BET, self)._run_interface(runtime)

  File "/Users/ivy/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 1029, in _run_interface
    runtime.hostname))

OSError: No command "bet" found on host my_computer. Please check that the corresponding package is installed.

Any help would be greatly appreciated! Thanks.

-Kirk

**Comment by satra** [comment]
@KirkGraff - it's very likely that Spyder does not initialize the environment in which it executes with your bash profile. if you start spyder from a terminal that has `bet` available it should work. 

https://stackoverflow.com/questions/47420268/how-to-set-path-variable-inside-spyder-on-ubuntu

**Comment by KirkGraff** [comment]
Thanks so much, that fixed it!
