### ISSUE TITLE
Running Gunzip doctest requires write access to the file

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#2835]
testing 1.1.7 as "system wide installed" on a debian system (sorry for a wide display) lead to
```
____________________________________________________________________________________________________________________________________ [doctest] nipype.algorithms.misc.Gunzip _____________________________________________________________________________________________________________________________________
268 Gunzip wrapper
269 
270     >>> from nipype.algorithms.misc import Gunzip
271     >>> gunzip = Gunzip(in_file='tpms_msk.nii.gz')
272     >>> res = gunzip.run()
UNEXPECTED EXCEPTION: IOError(13, 'Permission denied')
Traceback (most recent call last):

  File "/usr/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest nipype.algorithms.misc.Gunzip[2]>", line 1, in <module>

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)

  File "/usr/lib/python2.7/dist-packages/nipype/algorithms/misc.py", line 293, in _run_interface
    with open(self._gen_output_file_name(), 'wb') as out_file:

IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/nipype/testing/data/tpms_msk.nii'
```
I wonder if some nipype test run wide fixture could first copy testing data into a temp dir and then use it there if such `w` access is required?

**Comment by yarikoptic** [comment]
actually here is a few more of the same kind, which could be resolved with the above suggestion:

```
__________________________________________________________________________________________________________________________________ [doctest] nipype.interfaces.dcm2nii.Dcm2nii ___________________________________________________________________________________________________________________________________
105 
106     Examples
107     ========
108 
109     >>> from nipype.interfaces.dcm2nii import Dcm2nii
110     >>> converter = Dcm2nii()
111     >>> converter.inputs.source_names = ['functional_1.dcm', 'functional_2.dcm']
112     >>> converter.inputs.gzip_output = True
113     >>> converter.inputs.output_dir = '.'
114     >>> converter.cmdline  # doctest: +ELLIPSIS
UNEXPECTED EXCEPTION: IOError(13, 'Permission denied')
Traceback (most recent call last):

  File "/usr/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest nipype.interfaces.dcm2nii.Dcm2nii[5]>", line 1, in <module>

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base/core.py", line 954, in cmdline
    allargs = [self._cmd_prefix + self.cmd] + self._parse_inputs()

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base/core.py", line 1199, in _parse_inputs
    value = self._gen_filename(name)

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/dcm2nii.py", line 241, in _gen_filename
    with open(config_file, "w") as f:

IOError: [Errno 13] Permission denied: 'config.ini'

/usr/lib/python2.7/dist-packages/nipype/interfaces/dcm2nii.py:114: UnexpectedException
___________________________________________________________________________________________________________________________________ [doctest] nipype.interfaces.image.Reorient ___________________________________________________________________________________________________________________________________
133 .. testsetup::
134 
135     >>> def print_affine(matrix):
136     ...     print(str(matrix).replace(']', ' ').replace('[', ' '))
137 
138 >>> import numpy as np
139 >>> from nipype.interfaces.image import Reorient
140 >>> reorient = Reorient(orientation='LPS')
141 >>> reorient.inputs.in_file = 'segmentation0.nii.gz'
142 >>> res = reorient.run()
UNEXPECTED EXCEPTION: IOError(13, 'Permission denied')
Traceback (most recent call last):

  File "/usr/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest nipype.interfaces.image.Reorient[5]>", line 1, in <module>

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/image.py", line 204, in _run_interface
    np.savetxt(mat_name, affine_xfm, fmt='%.08f')

  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1307, in savetxt
    open(fname, 'wt').close()

IOError: [Errno 13] Permission denied: u'/usr/lib/python2.7/dist-packages/nipype/testing/data/segmentation0.mat'

/usr/lib/python2.7/dist-packages/nipype/interfaces/image.py:142: UnexpectedException
_______________________________________________________________________________________________________________________________ [doctest] nipype.interfaces.afni.preprocess.TShift _______________________________________________________________________________________________________________________________
2645     input:
2646 
2647     >>> from nipype.interfaces import afni
2648     >>> TR = 2.5
2649     >>> tshift = afni.TShift()
2650     >>> tshift.inputs.in_file = 'functional.nii'
2651     >>> tshift.inputs.tzero = 0.0
2652     >>> tshift.inputs.tr = '%.1fs' % TR
2653     >>> tshift.inputs.slice_timing = list(np.arange(40) / TR)
2654     >>> tshift.cmdline
UNEXPECTED EXCEPTION: IOError(13, 'Permission denied')
Traceback (most recent call last):

  File "/usr/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest nipype.interfaces.afni.preprocess.TShift[7]>", line 1, in <module>

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base/core.py", line 954, in cmdline
    allargs = [self._cmd_prefix + self.cmd] + self._parse_inputs()

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base/core.py", line 1203, in _parse_inputs
    arg = self._format_arg(name, spec, value)

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/afni/preprocess.py", line 2722, in _format_arg
    value = self._write_slice_timing()

  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/afni/preprocess.py", line 2727, in _write_slice_timing
    with open(fname, 'w') as fobj:

IOError: [Errno 13] Permission denied: 'slice_timing.1D'

```
