### ISSUE TITLE
AFNI's 3dmask_tool does not accept multiple mask files

### ISSUE THREAD

**Issue by hstojic** [nipy/nipype#2874]
### Summary

As far as I can see AFNI's `3dmask_tool` allows multiple masks as input, while it is not possible to input a list as `in_file` argument?

See [here](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dmask_tool.html) for details on the tool.

Error:
```python
Traceback (most recent call last):
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 408, in run
    cached, updated = self.is_cached()
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 294, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 488, in _get_hashval
    self._get_inputs()
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 531, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 276, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/nipype/interfaces/base/traits_extension.py", line 103, in validate
    validated_value = super(File, self).validate(object, name, value)
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/traits/trait_types.py", line 411, in validate
    self.error( object, name, value )
  File "/home/hstojic/.pyenv/nipy/local/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'in_file' trait of a MaskToolInputSpec instance must be an existing file name, but a value of ['mask_1',...,'mask_n'] <type 'list'> was specified.
```

### Execution environment

- My python environment outside container

**Comment by effigies** [comment]
You can probably fix this with an `InputMultiObject`, e.g.,

```Python
from ..base import InputMultiObject  # nipype.interfaces.base, to be clear

...

    in_file = InputMultiObject(File(exists=True), ...)
```

**Comment by hstojic** [comment]
Yes, that's what I thought of trying, but wanted to check first in case I missed something.

Thanks!
