### ISSUE TITLE
FSL MELODIC: better exit when it does not converge

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2914]
### Summary
MELODIC may not converge, and when that happens, the log is closed with a message:

```
No convergence -- giving up 
```

Since that is a possible (and valid) outcome, the interface should handle it correctly (instead of crashing).

### Actual behavior
The interface crashes with:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 523, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 131, in _post_run_hook
    return super(MELODICRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/mixins/reporting.py", line 47, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 120, in _generate_report
    report_mask=self.inputs.report_mask)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 527, in plot_melodic_components
    timeseries = np.loadtxt(os.path.join(melodic_dir, "melodic_mix"))
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 860, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/data/test_katenuss_mriqc/wdir/workflow_enumerator/funcMRIQC/_in_file_..data..hartleylab..memFreqMRI112..sub-112..func..sub-112_task-freq1_acq-normal_run-01_echo-3_bold.nii.gz/ICA/melodic_mix'
```

### Expected behavior
The interface finishes in a controlled way.

### How to replicate the behavior
To replicate this, it is necessary to run the interface on a dataset were convergence is not reached.

### Script/Workflow details
Comes from MRIQC (see poldracklab/mriqc#779 for a larger context)

**Comment by effigies** [comment]
This looks like a niworkflows bug. Since we're in `_post_run_hook`, `_run_interface` returned without error. Will open an issue on niworkflows.

**Comment by oesteban** [comment]
I don't think this is just a niworkflows bug. Not converging should be an expected result for this interface within Nipype and currently, it is not.

If you manually kill MELODIC while running, Nipype crashes exactly in the same way. That is not great.

**Comment by effigies** [comment]
Ah. Then I don't understand the issue.

**Comment by effigies** [comment]
Ah, just saw https://github.com/poldracklab/niworkflows/pull/337#issuecomment-481807370. So leaving aside the failure to converge (an acceptable, non-erroring exit), we should try to detect when MELODIC is killed with an OOM condition and raise an exception?

**Comment by oesteban** [comment]
Maybe, it would enough just redirect the `FileNotFoundError` to a `RuntimeError` with a more helpful description. MELODIC is not great at reporting exit codes, and I'm not sure we can use that information to provide more feedback than "The `melodic_mix` folder was not found. It may have been deleted by another process, or MELODIC failed for some unspecified reason (e.g. it was killed)".

**Comment by effigies** [comment]
The error that you posted above is being raised from niworkflows code, not nipype. If you want to address that error, this is not the place.

**Comment by oesteban** [comment]
After digging a little bit more I think you are right. Closing this for now.
