### ISSUE TITLE
New version 1.2.0 generates str error with mrTrix denoise, biascorrect

### ISSUE THREAD

**Issue by lucindasisk** [nipy/nipype#2975]
Hi! I have a DWI workflow that has run smoothly in Nipype version 1.1.8, utilizing mrTrix nodes including DWIDenoise. I upgraded to version 1.2.0 so I could incorporate MRDeGibbs (Gibbs ringing removal), but the denoising node generated the following error after running: "TypeError: expected str, bytes or os.PathLike object, not _Undefined". DWIBiasCorrect also generated same error. I downgraded to version 1.1.8 again, removed the Gibbs node, and everything ran smoothly. Thanks for any help!

### Script/Workflow details
**Node**
```
#Denoise DWI data using local PCA correction - mrTrix3
denoise = Node(mtx.DWIDenoise(),
              name='denoise')
```

**Workflow**
```
(drop2, denoise, [('roi_file', 'in_file')]),
                      (denoise, datasink, [('out_file', '1_Check_Unwarped.@par.@par.@par')])
```

### Platform details:
mac OS Mojave 10.14.5

**Comment by effigies** [comment]
Could you provide the full traceback and workflow? And can you verify that upgrading to 1.2.0 while not changing the script causes the problem?

**Comment by lucindasisk** [comment]
Definitely, thanks for your help! I just tested it again, and while it ran fine in version 1.1.8, it crashed again when I upgraded to 1.2.0. Happy to also test 1.1.9 if that would be helpful? Script is here: [https://github.com/lucindasisk/Diffusion/blob/master/1_DTI_Preprocessing-SHAPES.ipynb]. Traceback below:

```
Traceback (most recent call last):
  File "1_DTI_Preprocessing-SHAPES.py", line 247, in <module>
    preproc = preproc_flow.run('MultiProc', plugin_args={'n_procs': 4})
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 599, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 161, in run
    self._clean_queue(jobid, graph, result=result))
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 377, in run
    outputs = self.aggregate_outputs(runtime)
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/site-packages/nipype/interfaces/mrtrix3/preprocess.py", line 81, in _list_outputs
    outputs['out_file'] = op.abspath(self.inputs.out_file)
  File "/Users/lucindasisk/.local/share/virtualenvs/lucindasisk-jFZfvjp6/lib/python3.6/posixpath.py", line 369, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not _Undefined
```

**Comment by effigies** [comment]
Okay. It looks like this was introduce in #2904. @josephmje Could you clarify the reasons for the changes to DWIDenoise outputs? Looking at it, I don't immediately understand why `out_file` was changed.

**Comment by lucindasisk** [comment]
Thank you @effigies!

**Comment by josephmje** [comment]
Sorry @effigies @lucindasisk . I wanted to work with the output noise file in the rest of my workflow and modified the `_list_outputs()` method as suggested in the PR. But it looks like the change to the DWIDenoise class causes things to break unless `out_file` is specifically defined. 

I've been working through this by modifying the noise trait in `DWIDenoiseInputSpec` to:
```
    noise = File(
        argstr="-noise %s",
        name_template="%s_noise",
        name_source=["in_file"],
        keep_extension=True,
        desc="the output noise map",
    )
```
and removing the `_list_outputs()` method. But I'm not sure if this is the correct solution.

**Comment by oesteban** [comment]
Is the `-noise` argument optional?

**Comment by josephmje** [comment]
Yes it is.

**Comment by oesteban** [comment]
Then the name_template logic will include it automatically, so your suggestion has made it mandatory in practice. Do you know if there is any change in the methodology if you use `-noise`?

If it is just enabling the output, I don't think it would hurt to make it present always (via `name_template`).

**Comment by josephmje** [comment]
There is no change in the methodology by including `-noise`. The function creates it anyways but adding the option saves it to the filesystem.
