### ISSUE TITLE
doesn't fail if external is not actually available -- simply stalls

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#3]
so, trying to run example1.py, didn't setup my MATLABPATH to point to spm, so it is not available... running example simply stalls after puking little error which is barely detectable among the other output lines

$> python example1.py
PE: checking connections:

PE: finished checking connections

No clients found. running serially
Executing: Realign.spm H: c49a2f44ee83424c23f90790042e55b0
directory /home/yoh/proj/nipy/nipype.gitsvn/doc/examples/test3/Realign.spm exists

continuing to execute

copying /home/yoh/proj/nipy/nipype.gitsvn/doc/examples/data/s1/f3.nii to /home/yoh/proj/nipy/nipype.gitsvn/doc/examples/test3/Realign.spm/f3.nii
option cwd not supported

doing quick look:
$> strace -p 27588
Process 27588 attached - interrupt to quit
select(6, [3 5], [], [], NULL

C <unfinished ...>
Process 27588 detached

$> ls -l /proc/27588/fd/6
lr-x------ 1 yoh yoh 64 2009-10-07 09:43 /proc/27588/fd/6 -> pipe:[2800813]

So it waits for input which would never come? ;)

Here is a traceback I got after hitting Ctrl-C
Traceback (most recent call last):

    File "example1.py", line 37, in <module>

        pipeline.run()

    File "/home/yoh/proj/nipy/nipype.gitsvn/install/lib/python2.5/site-packages/nipype/pipeline/engine.py", line 221, in run

        self.run_in_series()

    File "/home/yoh/proj/nipy/nipype.gitsvn/install/lib/python2.5/site-packages/nipype/pipeline/engine.py", line 252, in run_in_series

        node.run()

    File "/home/yoh/proj/nipy/nipype.gitsvn/install/lib/python2.5/site-packages/nipype/pipeline/node_wrapper.py", line 135, in run

        self._run_interface(execute=True)

    File "/home/yoh/proj/nipy/nipype.gitsvn/install/lib/python2.5/site-packages/nipype/pipeline/node_wrapper.py", line 214, in _run_interface

        self._result = self._interface.run()

    File "/home/yoh/proj/nipy/nipype.gitsvn/install/lib/python2.5/site-packages/nipype/interfaces/spm.py", line 125, in run

        results = super(SpmMatlabCommandLine?,self).run()

    File "/home/yoh/proj/nipy/nipype.gitsvn/install/lib/python2.5/site-packages/nipype/interfaces/matlab.py", line 66, in run

        results = self._runner()

    File "/home/yoh/proj/nipy/nipype.gitsvn/install/lib/python2.5/site-packages/nipype/interfaces/base.py", line 273, in _runner

        runtime.stdout, runtime.stderr = proc.communicate()

    File "/usr/lib/python2.5/subprocess.py", line 670, in communicate

        return self._communicate(input)

    File "/usr/lib/python2.5/subprocess.py", line 1213, in _communicate

        rlist, wlist, xlist = select.select(read_set, write_set, [])

http://sourceforge.net/apps/trac/nipy/ticket/38

**Comment by satra** [comment]
this now raises an error.
