### ISSUE TITLE
ImportError: Could not import plugin module: nipype.pipeline.plugins

### ISSUE THREAD

**Issue by levchenkoegor** [nipy/nipype#3045]
Hi,

I am trying to run the code below, but several errors occur. I am not really sure about the exact problem of the code, because all of it it is just a copy from tutorials and documentations.

```
from nipype import SelectFiles, Node
import nipype.pipeline.engine as pe  # pypeline engine
import nipype.interfaces.spm as spm  # spm

templates = {'func': 'OAS3*/func{ses_id}/NIFTI/*.nii.gz'}
datasource = Node(SelectFiles(templates), name='selectfiles')
datasource.inputs.base_directory = r"D:\AD_OASIS3\AD_patients"
datasource.inputs.ses_id = 1

files = datasource.run().outputs.func
print(f'\n{len(files)} files were founded.')

realign = pe.Node(interface=spm.Realign(), name="realign")
realign.inputs.register_to_mean = True

smooth = pe.Node(interface=spm.Smooth(), name="smooth")
smooth.inputs.fwhm = 4

preprocessing = pe.Workflow(name="preprocessing")
preprocessing.connect(realign, "realigned_files", smooth, "in_files")

main_workflow = pe.Workflow(name="main_workflow")
main_workflow.base_dir = "output/wf"
main_workflow.connect(datasource, 'func', preprocessing, 'realign.in_files')

main_workflow.run()
```

```
190923-19:55:19,895 nipype.workflow INFO:
	 [Node] Setting-up "selectfiles" in "C:\Users\836D~1\AppData\Local\Temp\tmp_bnqtk_q\selectfiles".
190923-19:55:19,900 nipype.workflow INFO:
	 [Node] Running "selectfiles" ("nipype.interfaces.io.SelectFiles")
190923-19:55:19,929 nipype.workflow INFO:
	 [Node] Finished "selectfiles".
69 files were founded.
190923-19:55:20,381 nipype.workflow ERROR:
	 Could not import plugin module: nipype.pipeline.plugins
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\AD_func_conn\venv\lib\site-packages\nipype\pipeline\engine\workflows.py", line 576, in run
    __import__(name)
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Администратор\PycharmProjects\AD_func_conn\venv\lib\site-packages\nipype\pipeline\plugins\__init__.py", line 11, in <module>
    from .sge import SGEPlugin
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Администратор\PycharmProjects\AD_func_conn\venv\lib\site-packages\nipype\pipeline\plugins\sge.py", line 10, in <module>
    import pwd
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pwd'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Администратор\PycharmProjects\AD_func_conn\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-67b286819626>", line 29, in <module>
    main_workflow.run()
  File "C:\Users\Администратор\PycharmProjects\AD_func_conn\venv\lib\site-packages\nipype\pipeline\engine\workflows.py", line 580, in run
    raise ImportError(msg)
ImportError: Could not import plugin module: nipype.pipeline.plugins
```

My python environment outside container. I am using PyCharm to run the code and python 3.7.0 with nipype 1.2.2

Any suggestions will be very helpful.

**Comment by satra** [comment]
@levchenkoegor - on windows we would recommend running this using WSL. would that be possible?  

for this specific error we can limit which plugins are loaded by default on the platform.
