### ISSUE TITLE
The nipype.interfaces.base.interfaces.traits.Either class does not create an object with a "_metadata" attribute

### ISSUE THREAD

**Issue by servoz** [nipy/nipype#3056]
**To Reproduce and exception raised:**
```
% python3
Python 3.6.6 (default, Jul 19 2018, 16:29:00) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nipype.interfaces.base import InputMultiPath, traits
>>> from nipype.interfaces.spm.base import ImageFileSPM
>>> in_files = InputMultiPath(ImageFileSPM(exists=True), field='data', desc='list of files to smooth', mandatory=True, copyfile=False)
>>> in_files._metadata
{'field': 'data', 'desc': 'list of files to smooth', 'mandatory': True, 'copyfile': False, 'copy': 'deep'}
>>> fwhm = traits.Either(traits.List(traits.Float(), minlen=3, maxlen=3), traits.Float(), field='fwhm', desc='3-list of fwhm for each dimension')
>>> fwhm._metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 729, in __getattr__
    return getattr(self, "_metadata", {}).get(name, None)
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 729, in __getattr__
    return getattr(self, "_metadata", {}).get(name, None)
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 729, in __getattr__
    return getattr(self, "_metadata", {}).get(name, None)
  [Previous line repeated 328 more times]
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 718, in __getattr__
RecursionError: maximum recursion depth exceeded while calling a Python object
```
**Actual behavior:**
We use the _metadata attribute in [our codes](https://github.com/populse).
If a user want to define a multiple type input by using  the nipype.interfaces.base.traits.Either class, since the _metadata is not created it is observed a silent crash, due to the RecursionError exception that is raised. This is due to the traits/trait_handlers.TraitType.\_\_getattr\_\_(self, name) that return getattr(self, "_metadata", {}).get(name, None).
I haven't found time to see the nipype.interfaces.base.base.traits.Either class, and I don't know from where the issue comes from.
Any help will be very much appreciated.

**Platform details:**
```
190927-16:28:41,555 nipype.utils INFO:
	 Running nipype version 1.2.3-dev (latest: 1.2.3)
{'commit_hash': 'f7d7a1c27',
 'commit_source': 'installation',
 'networkx_version': '2.3',
 'nibabel_version': '2.3.1',
 'nipype_version': '1.2.3-dev',
 'numpy_version': '1.17.1',
 'pkg_path': '/home/toto/.local/lib/python3.6/site-packages/nipype-1.2.3.dev0+gf7d7a1c27-py3.6.egg/nipype',
 'scipy_version': '1.3.1',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.6.6 (default, Jul 19 2018, 16:29:00) \n'
                '[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]',
 'traits_version': '5.2.0.dev1219'}

```
**Execution environment:**
- My python environment outside container

**Comment by servoz** [comment]
This comes exclusively from the traits library, nothing to do with nipype.
```
% python3
Python 3.6.6 (default, Jul 19 2018, 16:29:00) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>  from traits.api import Either
>>>  from traits.api import Float, Int
>>> Float(2.0,field='data', desc='list of files to smooth', mandatory=True, copyfile=False)._metadata
{'field': 'data', 'desc': 'list of files to smooth', 'mandatory': True, 'copyfile': False}
>>> Either(Float(), Int(), field='fwhm', desc='3-list of fwhm for each dimension')._metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 729, in __getattr__
    return getattr(self, "_metadata", {}).get(name, None)
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 729, in __getattr__
    return getattr(self, "_metadata", {}).get(name, None)
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 729, in __getattr__
    return getattr(self, "_metadata", {}).get(name, None)
  [Previous line repeated 328 more times]
  File "/home/servoz/.local/lib/python3.6/site-packages/traits-5.2.0.dev1219-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 718, in __getattr__
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I'm not sure nipype will want to change something in the working of a private attribute... We will manage this issue directly in our library. I'm closing this ticket!
