### ISSUE TITLE
No such file or directory: 'result_bidssrc.pklz'

### ISSUE THREAD

**Issue by ebeanato** [nipy/nipype#3081]
Hello everyone,

### Summary
I am running fmriprep on a remote server.

### Actual behavior
During running, I have several time the same error:

"
Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:

Node: fmriprep_wf.single_subject_p001_wf.bids_info
	Interface: niworkflows.interfaces.bids.BIDSInfo
	Traceback:
Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 337, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 297, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 494, in _get_hashval
    self._get_inputs()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 521, in _get_inputs
    outputs = _load_resultfile(results_file)[0].outputs

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 300, in load_resultfile
    result = loadpkl(results_file)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 687, in loadpkl
    pkl_file = pklopen(infile.name, 'rb')

  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)

  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')

FileNotFoundError: [Errno 2] No such file or directory: 'result_bidssrc.pklz'
"

### Script/Workflow details
The main command is: docker run --rm -e DOCKER_VERSION_8395080871=19.03.2 -v /opt/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /path_to_data:/data:ro -v /path_to_data_output:/out poldracklab/fmriprep:1.5.0 /data /out participant --participant_label sub-p001 --fs-no-reconall

Thank you very much in advance!

**Comment by effigies** [comment]
Try installing 1.3.0rc1.

**Comment by effigies** [comment]
Sorry, I responded before I saw this was in the fMRIPrep context. Please try using fmriprep 1.5.1rc2.
