### ISSUE TITLE
bug report：FSL FIX "missing command"

### ISSUE THREAD

**Issue by yaowang1111** [nipy/nipype#3087]
It is weird that when i directly use fix in bash, everything works fine, but when i use nipype, the following error comes out:

Traceback (most recent call last):
  File "/gpfs/share/home/1801110663/git-repos/alexithymia/fix_wf.py", line 48, in <module>
    fix_wf=create_fix_wf()
  File "/gpfs/share/home/1801110663/git-repos/alexithymia/fix_wf.py", line 31, in create_fix_wf
    training=Node(Training(loo=True),name='training')
  File "/gpfs/share/home/1801110663/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 655, in __init__
    raise Exception("Missing command")
Exception: Missing command

**Comment by yaowang1111** [comment]
I found the solutions.
It seems that all FIX class use 'cmd' as command, however, the upper class CommandLine accept _cmd as command.
I'm not familiar with github pull request, so would any developers do that for me?
Thanks!
