### ISSUE TITLE
Current version of nipype is not working !

### ISSUE THREAD

**Issue by servoz** [nipy/nipype#3203]
that's the easiest issue to describe it I've ever had!:
```
>>> import nipype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+g47de76e6f-py3.7.egg/nipype/__init__.py", line 99, in <module>
    BaseInterface._etelemetry_version_data = check_latest_version()
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+g47de76e6f-py3.7.egg/nipype/__init__.py", line 86, in check_latest_version
    return etelemetry.check_available_version(
AttributeError: module 'etelemetry' has no attribute 'check_available_version'
>>> 

```

**Comment by satra** [comment]
i'm assuming you are using the latest pre-release. should be able to update with: `pip install --upgrade etelemetry` or if you install nipype itself with pip.

relevant package line: https://github.com/nipy/nipype/blob/master/nipype/info.py#L150

**Comment by servoz** [comment]
Oh, sorry, I didn't check the etelemetry version on my station... Thank you very much for your very quick response !
