### ISSUE TITLE
ModuleNotFoundError: No module named 'niworkflows.nipype'

### ISSUE THREAD

**Issue by mihirgandhi95** [nipy/nipype#3204]
Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:

	Node: workflow_enumerator.anatMRIQCT1w.ReportsWorkflow.PlotMosaicNoise
	Interface: mriqc.interfaces.viz.PlotMosaic
	Traceback:
Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 338, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 294, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 488, in _get_hashval
    self._get_inputs()

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 515, in _get_inputs
    results = loadpkl(results_file)

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 668, in loadpkl
    raise e

  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 659, in loadpkl
    unpkl = pickle.load(pkl_file)

ModuleNotFoundError: No module named 'niworkflows.nipype'

**Comment by oesteban** [comment]
Please update mriqc.

**Comment by effigies** [comment]
The issue seems to be that there is a working directory from a pre-0.11.0 MRIQC being reused with more recent MRIQC. The solution should be to delete the working directory.
