### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#3232]
### Summary
I am getting the following error from all my ANTs bias field correction nodes:

```
chymera@ihost ~/docsrc/opfvta/prepare $ nipypecli crash /home/chymera/.scratch/opfvta/crashdump/crash-20200805-014215-chymera-f_biascorrect.a00-9c5faaa4-c317-4a54-abef-658b91035d5d.pklz


File: /mnt/data/scratch/opfvta/crashdump/crash-20200805-014215-chymera-f_biascorrect.a00-9c5faaa4-c317-4a54-abef-658b91035d5d.pklz
Node: preprocess_work.f_biascorrect
Working directory: /mnt/data/scratch/opfvta/preprocess_work/_ind_type_6/f_biascorrect


Node inputs:

args = <undefined>
bias_image = <undefined>
bspline_fitting_distance = 10.0
bspline_order = 4
convergence_threshold = 1e-11
copy_header = False
dimension = 3
environ = {'NSLOTS': '1'}
histogram_sharpening = <undefined>
input_image = <undefined>
mask_image = <undefined>
n_iterations = [150, 100, 50, 30]
num_threads = 1
output_image = <undefined>
rescale_intensities = False
save_bias = False
shrink_factor = 2
weight_image = <undefined>



Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 353, in run
    self._check_version_requirements(self.inputs)
  File "/usr/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 279, in _check_version_requirements
    if min_ver > version:
  File "/usr/lib/python3.7/distutils/version.py", line 64, in __gt__
    c = self._cmp(other)
  File "/usr/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```

This is the command which the node lists:

```
N4BiasFieldCorrection --bspline-fitting [ 10, 4 ] -d 3 --input-image /mnt/data/scratch/opfvta/preprocess_work/_ind_type_100/temporal_mean/forced_dummy_scans_file_st_mean.nii.gz --convergence [ 150x100x50x30, 1e-11 ] --output forced_dummy_scans_file_st_mean_corrected.nii.gz --shrink-factor 2
```

The command works, so I think there's some overhead nipype version checking at work here, which prevents the node from ever being run.

I sadly have no idea how to disable this.  

### Platform details:

```
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.4',
 'nibabel_version': '3.0.2',
 'nipype_version': '1.5.0',
 'numpy_version': '1.19.1',
 'pkg_path': '/usr/lib/python3.7/site-packages/nipype',
 'scipy_version': '1.5.2',
 'sys_executable': '/usr/lib/python-exec/python3.7/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.8 (default, Jul 20 2020, 22:39:06) \n[GCC 9.3.0]',
 'traits_version': '6.0.0'}
chymera@ihost ~/docsrc/opfvt
```

### Execution environment

Choose one
- Container: no
- My python environment inside container: no
- My python environment outside container: python 3.7

**Comment by effigies** [comment]
Can you rerun (add `nipypecli crash -r`) with PDB (`-d`) or IPDB (`-i`) and see what `min_ver` and `version` are? From looking at it, both should be `LooseVersion`s:

https://github.com/nipy/nipype/blob/5116ee208205c8050f87fc2a45bb0f35e3dd1c0a/nipype/interfaces/base/core.py#L275-L287

**Comment by TheChymera** [comment]
@effigies I'm not sure how to query those variables:

```
chymera@ihost ~/docsrc/opfvta/prepare $ nipypecli crash -rd /home/chymera/.scratch/opfvta/crashdump/crash-20200805-014215-chymera-f_biascorr
ect.a00-9c5faaa4-c317-4a54-abef-658b91035d5d.pklz


File: /mnt/data/scratch/opfvta/crashdump/crash-20200805-014215-chymera-f_biascorrect.a00-9c5faaa4-c317-4a54-abef-658b91035d5d.pklz
Node: preprocess_work.f_biascorrect
Working directory: /mnt/data/scratch/opfvta/preprocess_work/_ind_type_6/f_biascorrect


Node inputs:

args = <undefined>
bias_image = <undefined>
bspline_fitting_distance = 10.0
bspline_order = 4
convergence_threshold = 1e-11
copy_header = False
dimension = 3
environ = {'NSLOTS': '1'}
histogram_sharpening = <undefined>
input_image = <undefined>
mask_image = <undefined>
n_iterations = [150, 100, 50, 30]
num_threads = 1
output_image = <undefined>
rescale_intensities = False
save_bias = False
shrink_factor = 2
weight_image = <undefined>



Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 353, in run
    self._check_version_requirements(self.inputs)
  File "/usr/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 279, in _check_version_requirements
    if min_ver > version:
  File "/usr/lib/python3.7/distutils/version.py", line 64, in __gt__
    c = self._cmp(other)
  File "/usr/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'



Rerunning node
200805-16:02:07,782 nipype.workflow INFO:
         [Node] Setting-up "preprocess_work.f_biascorrect" in "/mnt/data/scratch/opfvta/preprocess_work/_ind_type_6/f_biascorrect".
200805-16:02:07,827 nipype.workflow INFO:
         [Node] Running "f_biascorrect" ("nipype.interfaces.ants.segmentation.N4BiasFieldCorrection"), a CommandLine Interface with command:
N4BiasFieldCorrection --bspline-fitting [ 10, 4 ] -d 3 --input-image /mnt/data/scratch/opfvta/preprocess_work/_ind_type_6/temporal_mean/forced_dummy_scans_file_st_mean.nii.gz --convergence [ 150x100x50x30, 1e-11 ] --output forced_dummy_scans_file_st_mean_corrected.nii.gz --shrink-factor 2
200805-16:02:07,894 nipype.workflow WARNING:
         Storing result file without outputs
200805-16:02:07,894 nipype.workflow WARNING:
         [Node] Error on "preprocess_work.f_biascorrect" (/mnt/data/scratch/opfvta/preprocess_work/_ind_type_6/f_biascorrect)
> /usr/lib/python3.7/distutils/version.py(337)_cmp()
-> if self.version < other.version:
(Pdb) min_ver
*** NameError: name 'min_ver' is not defined
(Pdb) version
*** NameError: name 'version' is not defined
```

**Comment by TheChymera** [comment]
@effigies ah, ok, I have it:

```
(Pdb) self.version
[2, 1, 0]
(Pdb) other.version
['snapshot']
```

Is there any way to tell nipype to stop trying to check my versions? In as far as there are restrictions those are better covered via my package manager.

**Comment by effigies** [comment]
Ah, thank you.

So it looks like this is probably the case?

```
$ antsRegistration --version
...
ANTs Version: snapshot
...
```

If there's better version information to parse out of that, we can do that. Returning `None` would short-circuit that code, which might be appropriate, as no version check will work. Another option could be a `Development` object that is `>=` any `LooseVersion`, to distinguish a missing tool installation from an unversioned (and therefore probably bleeding edge) installation.

And we could probably add a configuration option to disable version checks.

**Comment by TheChymera** [comment]
@effigies well, it's:

```
chymera@silenthost ~ $ antsRegistration --version
ANTs Version: snapshot-2.3.4
Compiled: Aug  4 2020 14:40:52
```

I guess this could be solved in ANTs (as mentioned here: https://github.com/ANTsX/ANTs/issues/1059#issuecomment-669483459) but I think the better solution is for this to be easily turned off in nipype. I think having a package handle its own dependency management is a bit of mission creep which muddies the waters for system administrators.

I don't remember this happening with earlier versions. Do you know when this was introduced and whether it's easily patchable?

**Comment by satra** [comment]
we could patch ants' version reader, but as i commented on the ants issue, i think they should switch back to proper semantic versioning, which is what we expect in the version code.

nipype has had versioned based input keys for a long time. and is simply checking whether a particular input key is available for that version of ants. many software tools have either removed or introduced keys in different versions of the software. nipype sometimes catches these.

**Comment by TheChymera** [comment]
@satra @effigies 

What do you say to this?

```patch
--- nipype/interfaces/base/core.py	2020-08-06 02:07:56.750154463 -0400
+++ /home/chymera/lala	2020-08-06 02:08:23.344434883 -0400
@@ -276,6 +276,15 @@
             version = LooseVersion(str(self.version))
             for name in names:
                 min_ver = LooseVersion(str(trait_object.traits()[name].min_ver))
+                try:
+                    min_ver > version
+                except:
+                    print(
+                        'Nipype is having issues parsing the package version '
+                        'for Trait {} ({})'
+                        'You may want to check whehter {} is larger than {}'
+                        .format(name, self.__class__.__name__, version, min_ver)
+                        )
                 if min_ver > version:
                     unavailable_traits.append(name)
                     if not isdefined(getattr(trait_object, name)):
```

**Comment by satra** [comment]
@TheChymera - sounds reasonable. i would change the print to the `iflogger` and if possible make the exception a bit more specific. i think `TypeError` is a reasonable one here since any errors should only be about the comparator.
