### ISSUE TITLE
workflow crashes while writing crashfiles with plugin SLURM

### ISSUE THREAD

**Issue by myosotisleila** [nipy/nipype#3372]
### Summary
Hello,

I have some trouble with a workflow that could be a bug. 
I made a (small) nipype pipeline that run fine in linear mode (no plugin) or with the "multiproc" plugin.
It runs with no crash and gives all the expected results. 

However, when I try to run it with "slurm" plugin, it crashes AND gives an error while writing the crashfile. 

### Actual behavior

The crashing node is the first node with a custom interface. Before that, it runs normally on slurm.

I have run lots of custom interfaces before in nipype (but on older versions, like 0.12) with no problems using slurm. 

Since there is an error while writing the crashfile, I only have this error message : 

```Traceback (most recent call last):
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/plugins/tools.py", line 28, in report_crash
    result = node.result
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 217, in result
    op.join(self.output_dir(), "result_%s.pklz" % self.name)
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /bigdata/SHIVA/data/Nifti/ukbiobank1/processviolaine/slurmtest/preprocessing_ukbiobank/_subject_id_1211915/T1Normalization/result_T1Normalization.pklz

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes_unix/verrecchia/svn/SHIVA/trunk/preprocessing/preprocessing_ukbiobank.py", line 349, in <module>
    workflow.run(plugin='SLURM')  # run with slurm, doesn't work for now
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 164, in run
    self._clean_queue(jobid, graph, result=result)
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 225, in _clean_queue
    crashfile = self._report_crash(self.procs[jobid], result=result)
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 209, in _report_crash
    return report_crash(node, traceback=tb)
  File "/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype/pipeline/plugins/tools.py", line 34, in report_crash
    keepends=True
TypeError: can only concatenate str (not "list") to str
```

### Expected behavior
The expected behavior is : 
1. To work around the crashfile writing issue, so I know what exactly happened in the workflow (that does not happen in multiproc)
2. to solve this crash and understand why it happens only with slurm, and not on multiproc plugin or without plugin.

### Script/Workflow details
The first few nodes (the ones running normally) are basic datagrabber, unzipping of some files with Gunzip, registration with FLIRT and application of a deformation field (from FLIRT) to another file with ApplyXML.

The node that crashes is a custom interface node wrapping a matlab script. 

### Platform details:
```
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.4',
 'nibabel_version': '3.1.1',
 'nipype_version': '1.5.0',
 'numpy_version': '1.18.4',
 'pkg_path': '/homes_unix/verrecchia/.conda/vrs/lib/python3.7/site-packages/nipype',
 'scipy_version': '1.4.1',
 'sys_executable': '/homes_unix/verrecchia/.conda/vrs/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.6 | packaged by conda-forge | (default, Jun  1 2020, '
                '18:57:50) \n'
                '[GCC 7.5.0]',
 'traits_version': '6.0.0'}
```

### Execution environment
nipype version 1.5.0
Python version 3.7.6
slurm version 18.08.0
OS is centos 7

This has also been tried on another machine with another slurm grid, nipype 1.6.0 and Python 3.7.9, with the same behavior.

Thank you in advance for you help.

**Comment by JRJacoby** [comment]
I'm getting this same exact thing. Any ideas what's going on?
