### ISSUE TITLE
ANTSRegistration() error formatting command line argument 'transforms'

### ISSUE THREAD

**Issue by ramroomh** [nipy/nipype#3591]
### Summary

I am attempting to run the Registration() wrapper from ANTS using ['Rigid','Affine','SyN'] as input to transforms.

### Actual behavior

`nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node antsreg_t1_to_mni.

Traceback:
	Traceback (most recent call last):
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 937, in _parse_inputs
	    arg = self._format_arg(name, spec, value)
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 1285, in _format_arg
	    return self._format_registration()
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 1142, in _format_registration
	    retval.append("--transform %s" % (self._format_transform(ii)))
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 1133, in _format_transform
	    [str(element) for element in self.inputs.transform_parameters[index]]
	TypeError: '_Undefined' object is not subscriptable

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 737, in _run_interface
	    runtime.cmdline = self.cmdline
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 662, in cmdline
	    allargs = [self._cmd_prefix + self.cmd] + self._parse_inputs()
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 941, in _parse_inputs
	    ) from exc
	ValueError: Error formatting command line argument 'transforms' with value '['Rigid', 'Affine', 'SyN']'

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 399, in run
	    runtime = self._run_interface(runtime)
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 1020, in _run_interface
	    runtime = super(Registration, self)._run_interface(runtime)
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 741, in _run_interface
	    ) from exc
	RuntimeError: Error raised when interpolating the command line
`
### Expected behavior

I expect the registration to execute rigid, affine, the SyN registration using an MNI template (fixed) and T1 (moving).

### How to replicate the behavior

Here is the node:
`antsreg_t1_to_mni = Node(Registration(), name='antsreg_t1_to_mni')
antsreg_t1_to_mni.inputs.dimension = 3
antsreg_t1_to_mni.inputs.output_transform_prefix = "t1_to_mni_"
antsreg_t1_to_mni.inputs.transforms = ['Rigid', 'Affine', 'SyN']
antsreg_t1_to_mni.inputs.number_of_iterations = [[1000,500,250,0]*3]
antsreg_t1_to_mni.inputs.write_composite_transform = True
antsreg_t1_to_mni.inputs.collapse_output_transforms = False
antsreg_t1_to_mni.inputs.initialize_transforms_per_stage = False
antsreg_t1_to_mni.inputs.metric = ['CC']*3
antsreg_t1_to_mni.inputs.convergence_threshold = [1.e-8]*3
antsreg_t1_to_mni.inputs.smoothing_sigmas = [[3,2,1,0]*3]
antsreg_t1_to_mni.inputs.shrink_factors = [[8,4,2,1]*3]
antsreg_t1_to_mni.inputs.use_histogram_matching = [True, True, True] `

### Script/Workflow details

Here is the partial workflow:
`(imgtemplates, antsreg_t1_to_mni, [('mnitemplate', 'fixed_image')]),
(T1w, antsreg_t1_to_mni, [('T1w', 'moving_image')]),
`

Please put URL to code or code here (if not too long).

### Platform details:

```
{'commit_hash': '75796d554',
 'commit_source': 'installation',
 'networkx_version': '2.5.1',
 'nibabel_version': '3.0.1',
 'nipype_version': '1.8.7.dev0',
 'numpy_version': '1.18.1',
 'pkg_path': '/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype',
 'scipy_version': '1.7.3',
 'sys_executable': '/group/tuominen/anaconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]',
 'traits_version': '5.2.0'}
```

### Execution environment

- My python environment outside container

**Comment by effigies** [comment]
```
	Traceback (most recent call last):
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 937, in _parse_inputs
	    arg = self._format_arg(name, spec, value)
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 1285, in _format_arg
	    return self._format_registration()
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 1142, in _format_registration
	    retval.append("--transform %s" % (self._format_transform(ii)))
	  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 1133, in _format_transform
	    [str(element) for element in self.inputs.transform_parameters[index]]
	TypeError: '_Undefined' object is not subscriptable
```

You need to define `transform_parameters`.

**Comment by ramroomh** [comment]
Thank you. Sorry for the oversight, I guess I was confused because it is not explicitly stated as a mandatory input. Registration now runs.

**Comment by effigies** [comment]
Glad to hear!
