### ISSUE TITLE
AttributeError: 'PythonQtStdOutRedirect' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by sarafv** [nipy/nipype#3649]
### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

```

```

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by sarafv** [comment]
I had  installed nipype with pip install on 3D Slicer python (3.9) without errors but when I do 
import nipype on the python shell I get : 

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/sara.fernandezvidal/thirdPartySoftwareStim/Slicer-5.6.1-linux-amd64/lib/Python/lib/python3.9/site-packages/nipype/__init__.py", line 28, in <module>
    faulthandler.enable()
AttributeError: 'PythonQtStdOutRedirect' object has no attribute 'fileno'
```
