### ISSUE TITLE
TypeError: Cannot cast array data from dtype('uint64') to dtype('int64') according to the rule 'safe'

### ISSUE THREAD

**Issue by dominicjob** [nipy/nipype#730]
The image:
https://dl.dropboxusercontent.com/u/9564878/meana_X_fMRI4s004a1001_roi.nii

$ python /home/dataman/pipelines/case_studies/src/pipeline.py

/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/cmtk/nx.py:32: UserWarning: cmp not installed
  warnings.warn('cmp not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/cmtk/parcellation.py:30: UserWarning: cmp not installed
  warnings.warn('cmp not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/cmtk/convert.py:26: UserWarning: cfflib not installed
  warnings.warn('cfflib not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/cmtk/nbs.py:20: UserWarning: ConnectomeViewer not installed
  warnings.warn('ConnectomeViewer not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/mrtrix/convert.py:28: UserWarning: dipy not installed
  warnings.warn('dipy not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/dipy/tracks.py:17: UserWarning: dipy not installed
  warnings.warn('dipy not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/workflows/dmri/connectivity/group_connectivity.py:13: UserWarning: cmp not installed
  warnings.warn('cmp not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/workflows/dmri/mrtrix/group_connectivity.py:13: UserWarning: cmp not installed
  warnings.warn('cmp not installed')
/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/algorithms/rapidart.py:269: UserWarning: Deprecation warning: "bound_by_brainmask" will be set to Truein release 0.8
  warn(('Deprecation warning: "bound_by_brainmask" will be set to True'
Traceback (most recent call last):
  File "/home/dataman/pipelines/case_studies/src/pipeline.py", line 339, in <module>
    main_pipeline.run(plugin='MultiProc', plugin_args={'n_procs': 4})
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 519, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/base.py", line 242, in run
    result=result))
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/base.py", line 271, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/base.py", line 231, in run
    result=result))
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/base.py", line 271, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 15, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1128, in run
    self._run_interface()
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1226, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/pipeline/engine.py", line 1350, in _run_command
    result = self._interface.run()
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/base.py", line 895, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipype-0.0.0-py2.7.egg/nipype/interfaces/nipy/preprocess.py", line 56, in _run_interface
    brain_mask = compute_mask(**args)
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipy/labs/mask.py", line 242, in compute_mask
    mask = largest_cc(mask)
  File "/usr/local/anaconda/lib/python2.7/site-packages/nipy/labs/mask.py", line 41, in largest_cc
    label_count = np.bincount(labels.ravel())
TypeError: Cannot cast array data from dtype('uint64') to dtype('int64') according to the rule 'safe'
Interface ComputeMask failed to run. Inputs:
M = <undefined>
cc = <undefined>
ignore_exception = False
m = <undefined>
mean_volume = /work/meana_X_fMRI4s004a1001_roi.nii
reference_volume = <undefined>

**Comment by mgxd** [comment]
this has been fixed
