### ISSUE TITLE
JoinNode requires networkx 1.6 but Nipype only requires networkx 1.5

### ISSUE THREAD

**Issue by thelxinoe** [nipy/nipype#846]
It causes the following error.

Traceback (most recent call last):
  File "fslWyethICA.py", line 352, in <module>
    connections.write_graph(graph2use='exec')
  File "/usr/lib/python2.6/site-packages/nipype/pipeline/engine.py", line 542, in write_graph
    graph = generate_expanded_graph(deepcopy(graph))
  File "/usr/lib/python2.6/site-packages/nipype/pipeline/utils.py", line 592, in generate_expanded_graph
    and nx.has_path(graph_in, inode, node)]
AttributeError: 'module' object has no attribute 'has_path'

My code to reproduce is the following:

https://gist.github.com/thelxinoe/4df88d01a60967a7e331

**Comment by mgxd** [comment]
closing now that we require 1.7
