### ISSUE TITLE
 fmri_spm_nested tutorial won't work.

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#874]
In [my search for a level1&2 nipype tutorial](https://groups.google.com/forum/#!topic/nipy-user/AS6TSKYLfNs) I also tried this one out. [This line](https://github.com/nipy/nipype/blob/f34ab50a576d884a12f9684d737175eda82516bb/examples/fmri_spm_nested.py#L101) says the missing file is somehow included in the distribution, perhaps a link to the file from the repo would help, as it takes a while to find it among the installed files on your machine.

In any case, after I moved the file to a location wher python would find it, I am still getting this error:

```
/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py:376: UserWarning: Input all_axial requires inputs: image_width
  warn(msg)
140705-03:13:11,293 workflow INFO:
	 ['check', 'execution', 'logging']
Subject ID: s3

Subject ID: s1

140705-03:13:11,371 workflow INFO:
	 Running serially.
140705-03:13:11,373 workflow INFO:
	 Executing node datasource.c0 in dir: /home/chymera/src/faceOM/analysis/spm_tutorial2/workingdir/level1/_subject_id_s1/datasource
140705-03:13:11,397 workflow ERROR:
	 ['Node datasource.c0 failed to run on host desktophost.']
140705-03:13:11,398 workflow INFO:
	 Saving crash info to /home/chymera/src/faceOM/analysis/crash-20140705-031311-chymera-datasource.c0.pklz
140705-03:13:11,398 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1391, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1501, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1627, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 959, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1030, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/io.py", line 550, in _list_outputs
    raise IOError(msg)
IOError: Output key: struct Template: /home/chymera/src/faceOM/analysis/data/s1/struct.nii returned no files
Interface DataGrabber failed to run. 

140705-03:13:11,402 workflow INFO:
	 Executing node datasource.c1 in dir: /home/chymera/src/faceOM/analysis/spm_tutorial2/workingdir/level1/_subject_id_s3/datasource
140705-03:13:11,413 workflow ERROR:
	 ['Node datasource.c1 failed to run on host desktophost.']
140705-03:13:11,413 workflow INFO:
	 Saving crash info to /home/chymera/src/faceOM/analysis/crash-20140705-031311-chymera-datasource.c1.pklz
140705-03:13:11,414 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1391, in run
    self._run_interface()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1501, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 1627, in _run_command
    result = self._interface.run()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 959, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/base.py", line 1030, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/usr/lib64/python2.7/site-packages/nipype/interfaces/io.py", line 550, in _list_outputs
    raise IOError(msg)
IOError: Output key: struct Template: /home/chymera/src/faceOM/analysis/data/s3/struct.nii returned no files
Interface DataGrabber failed to run. 

140705-03:13:11,416 workflow INFO:
	 ***********************************
140705-03:13:11,416 workflow ERROR:
	 could not run node: level1.datasource.c0
140705-03:13:11,416 workflow INFO:
	 crashfile: /home/chymera/src/faceOM/analysis/crash-20140705-031311-chymera-datasource.c0.pklz
140705-03:13:11,416 workflow ERROR:
	 could not run node: level1.datasource.c1
140705-03:13:11,417 workflow INFO:
	 crashfile: /home/chymera/src/faceOM/analysis/crash-20140705-031311-chymera-datasource.c1.pklz
140705-03:13:11,417 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "fmri_level2.py", line 422, in <module>
    level1.run()
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/engine.py", line 693, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 56, in run
    report_nodes_not_run(notrun)
  File "/usr/lib64/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 92, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```

Could you help me out?

**Comment by AnjaliPullabhotla** [comment]
IOError: bet could not be found on host desktophost.fritz.box
Interface BET failed to run. 

Hi - I'm getting the same error 
Were you able to resolve it?

**Comment by oesteban** [comment]
duplicate of #2266.

@AnjaliPullabhotla please see https://github.com/nipy/nipype/issues/2266#issuecomment-340851449
