### ISSUE TITLE
Cannot view crash files

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#875]
I am dealing with some crashes that output `.pklz` files. These appear to not be human-readable. After having to use Google search for quite a bit I finally found out that them not being readable is intended (why?), and that they can be opened with the obscure `nipype_display_crash` function. Sadly, while this solution is specified, there are no instructions available on how to actually import this function.

Here area few lines of what didn't work:

``` python
Python 2.7.6 (default, May  2 2014, 21:01:44) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nipype as ni
>>> ni.nipype_display_crash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'nipype_display_crash'
>>> ni.utils.nipype_display_crash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'nipype_display_crash'
>>> ni.utils.nipype_display_crash()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'nipype_display_crash'
>>> ni.nipype_display_crash()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'nipype_display_crash'
>>> ni.utils.filemanip.nipype_display_crash()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'nipype_display_crash'
>>> nipype_display_crash()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'nipype_display_crash' is not defined
>>> from nipype import nipype_display_crash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name nipype_display_crash
>>> from nipype.utils import nipype_display_crash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name nipype_display_crash
>>> from nipype.utils.filemanip import nipype_display_crash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name nipype_display_crash
>>> from nipype.bin import nipype_display_crash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named bin
```

Could you please tell me how I could read these files and add some documentation for this process (as my Google search revealed, there are many others who find this confusing).

**Comment by LJWilliams** [comment]
`nipype_display_crash` seems to be deprecated. Try the commands from here

(http://nipype.readthedocs.io/en/latest/users/cli.html)[http://nipype.readthedocs.io/en/latest/users/cli.html]
